rackerlabs/repose

repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/experimental/servletContract/ServletContractFilterTest.groovy
Updated the comments to reflect that this issue is fully documented in REP-320.
Updated the deprecated Date() creation to use a GregorianCalendar().
=> Kicking the can again until June 2015 on full Servlet Contract support.

repose-aggregator/installation/build-system-packages.sh, repose-aggregator/installation/deb/repose-test-trusty-server-cloudimg-amd64.sh, repose-aggregator/installation/rpm/repose-test-centos-65-x64-virtualbox-puppet.sh, repose-aggregator/installation/rpm/repose-test-genric-rpm.sh
After getting word that the nightly master builds had been failing, I took a closer look at the test scripts to ensure they were able to still execute. I found the artifact names had not been updated in the Vagrant test scripts. Along the way I found some other odds and ends stuff that needed cleaned up in order prevent littering the file system. I also added in some time stats to the Vagrant test harnesses. I don't think these changes were keeping the nightly builds from executing, but they were updates that needed to be made.
=> Updated the name of the RPM artifacts to be installed in the Vagrant tests.

repose-aggregator/commons/utilities/src/main/java/org/openrepose/commons/utils/proxy/RequestProxyService.java, repose-aggregator/core/core-lib/src/main/java/org/openrepose/core/services/httpcomponent/RequestProxyServiceImpl.java, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/core/proxy/ConnectionManagementTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/core/proxy/MisbehavingOriginTest.groovy
Originally the problem was that a backend API was returning "null\r\n"
That's obviously a problem with the backend service, however, repose was blowing up with a foolish NullPointerException, which isn't valid at all. This cleans that up, and if the backend gives us a protocol exception, we'll return a 502 Bad Gateway, instead of just an internal server error.
=> Rep 1674 failure cleanup

repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/derp/DerpAndClientAuthNDelegable.groovy
This error message was normalized in REP-1526 Akka Client NPE. Since this test doesn't execute as part of the normal build cycle, it did not get caught until the nightly after the merge.
=> Fixed the expected error message in a test that doesn't run in the normal Jenkins build.

repose-aggregator/components/filters/add-header/src/test/scala/org/openrepose/filters/addheader/AddHeaderHandlerTest.scala, repose-aggregator/components/filters/derp/src/test/scala/org/openrepose/filters/derp/DerpFilterTest.scala, repose-aggregator/components/filters/forwarded-proto/src/test/scala/org/openrepose/filters/forwardedproto/ForwardedProtoFilterTest.scala, repose-aggregator/components/filters/herp/src/test/scala/org.openrepose.filters.herp/HerpFilterTest.scala, repose-aggregator/components/filters/iri-validator/src/test/scala/org/openrepose/filters/irivalidator/IriValidatorFilterTest.scala, repose-aggregator/components/filters/openstack-identity-v3/src/test/scala/org/openrepose/filters/openstackidentityv3/utilities/OpenStackIdentityV3APITest.scala, repose-aggregator/components/filters/rackspace-identity-basic-auth/src/test/scala/org/openrepose/filters/rackspaceidentitybasicauth/BasicAuthUtilsTest.scala
Since the seven Scala test classes containing these 25 tests weren't annotated, the tests weren't running as part of the normal build process.
The tests could be manually executed and all were currently passing, but they would not have failed a build.
=> Fix scala tests not running.

repose-aggregator/core/core-lib/src/main/resources/log4j2.xml, repose-aggregator/core/core-lib/src/main/resources/org/openrepose/core/services/logging/log4j2-DEFAULT.xml, repose-aggregator/core/valve/pom.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/common/log4j2-test.xml, repose-aggregator/installation/configs/core/log4j2.xml
So the problem seems to have arisen from the Log4j2Plugins.dat file which was generated and made its way into our fat jar. I am not 100% certain why that broke things (maybe the plugin was generated for the flume appender jar and moving it into our fat jar messed everything up?) but changing the mechanism log4j2 uses to load the plugin at least got our logs back.
I have also not yet tested this. I'm going to let the PR builder test our current system test suite, and I imagine our new Repose to Flume tests will make sure the appender is working.
A couple of other things to consider:
1. We may be able to prevent the Log4j2Plugins.dat file from being generated rather than excluding it in the shader plugin.
2. There are a couple of other ways we could add the plugin without changing the …
=> Flume Appender Fix

repose-aggregator/experimental/servlet-contract-filter/src/main/java/org/openrepose/experimental/filters/servletcontract/ResponseCaptureFilter.java
Added a SuppressWarnings annotation to ignore Sonar rule "Define and throw a dedicated exception instead of using a generic one." (squid:S00112) in this test class.
Replaced all of the System.out/err calls with equivalent Logger calls.
Added a comment to the empty destroy() method to prevent triggering squid:S1186.
=> Clearing TechDebt in the ResponseCaptureFilter class

repose-aggregator/extensions/api-validator/pom.xml, repose-aggregator/installation/rpm/repose-cli-utils/pom.xml, repose-aggregator/installation/rpm/repose-extensions-filter-bundle/pom.xml, repose-aggregator/installation/rpm/repose-filter-bundle/pom.xml, repose-aggregator/installation/rpm/repose-valve/pom.xml, repose-aggregator/installation/rpm/repose-war/pom.xml
See: #1264 
This does work contrary to the documentation referenced by the plugin (http://www.rpm.org/max-rpm-snapshot/s1-rpm-depend-manual-dependencies.html). I have submitted a patch to the RPM Maven Plugin team to update the documentation to reflect this.
=> REP-1885 Updated the RPM packages to use Versioned Virtual Packages

repose-aggregator/core/core-lib/src/main/java/org/openrepose/core/services/config/impl/ConfigurationServiceImpl.java, repose-aggregator/core/core-lib/src/test/groovy/org/openrepose/core/services/config/impl/ConfigurationServiceImplTest.groovy
Changed the order in which things happen when subscribing to stop accidental double event triggers
=> config service fix for double eventing

repose-aggregator/installation/configs/etc/logrotate.d/repose
When logrotate rotates the repose logs, the result is empty log files because the file handle being written is still the old file.  The solution is to configure logrotate with copytruncate so that it copies the file and repose will continue to write to the old file handle.
=> Adding copytruncate to logrotate to stop empty files

repose-aggregator/installation/deb/pom.xml, repose-aggregator/installation/rpm/pom.xml, repose-aggregator/pom.xml
This requires the Repose Signing Keys and Passphrase ver. 3 dated Mar 26, 2015 to be on the Jenkins Master and Slaves before the final test can be executed.
=> REP-1869 Update POM's to sign RPM and DEB artifacts.

repose-aggregator/commons/configuration/src/test/resources/unmarshallerValidator/xsd/openstack-identity-v3.xsd, repose-aggregator/components/filters/openstack-identity-v3/pom.xml, repose-aggregator/components/filters/openstack-identity-v3/src/main/resources/META-INF/schema/config/openstack-identity-v3.xsd, repose-aggregator/components/filters/openstack-identity-v3/src/main/resources/META-INF/schema/examples/openstack-identity-v3.cfg.xml, repose-aggregator/components/filters/openstack-identity-v3/src/main/scala/org/openrepose/filters/openstackidentityv3/objects/OpenStackIdentityV3Objects.scala, repose-aggregator/components/filters/openstack-identity-v3/src/main/scala/org/openrepose/filters/openstackidentityv3/utilities/OpenStackIdentityV3API.scala, repose-aggregator/components/filters/openstack-identity-v3/src/test/scala/org/openrepose/filters/openstackidentityv3/utilities/OpenStackIdentityV3APITest.scala, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/identityv3/withdomain/openstack-identity-v3.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/identityv3/AdminDomainTest.groovy
This sets up the Openstack V3 API class to be able to append a 
```json
"domain":{
"id": "someConfiguredId"
}
```
in the request for an admin token for the Openstack V3 filter.
=> Rep 1980 osv3 domain

repose-aggregator/core/valve/src/main/scala/org/openrepose/valve/ReposeJettyServer.scala, repose-aggregator/core/valve/src/main/scala/org/openrepose/valve/Valve.scala, repose-aggregator/core/valve/src/main/scala/org/openrepose/valve/jmx/ValvePortMXBean.scala, repose-aggregator/core/valve/src/main/scala/org/openrepose/valve/jmx/ValvePortMXBeanImpl.scala, repose-aggregator/core/valve/src/main/scala/org/openrepose/valve/spring/ValveRunner.scala, repose-aggregator/core/valve/src/test/scala/org/openrepose/spring/ValveTestModeRunnerTest.scala
This adds a --test-mode to valve's command line parameters and sets up a JMX bean to allow introspection of the running Jettys so that we can start up valve on potentially many random ports.
This is one of the steps necessary to implement parallelized functional testing, allowing the JVM to select it's own ports for the things that are running.
Note that this does not do randomized ports for the dist-datastore.
=> Valve test mode

repose-aggregator/installation/rpm/repose-valve/pom.xml, repose-aggregator/installation/rpm/repose-war/pom.xml
Lines were truncated and chopped in shell scripts, cleaned up lines to preserve line length and still allow shell scripts to execute.
=> pre-install scripts need updated due to formatting changes

repose-aggregator/core/core-lib/src/main/java/org/openrepose/core/spring/CoreSpringProvider.java, repose-aggregator/core/core-lib/src/main/resources/springConfiguration.conf, repose-aggregator/core/core-lib/src/test/resources/springConfiguration.conf, repose-aggregator/core/core-lib/src/test/scala/org/openrepose/core/spring/CoreSpringProviderTest.scala
Replaces #1304 by using the typesafe config library to it's full potential.
It works the same way:
```
java -DextendedSpringContextPath=com.somewhere -cp ./external.jar -jar repose-valve.jar -c /etc/repose
```
This will also scan the package `com.somewhere`, assuming it's provided by the external.jar
=> Vishal kedia master

repose-aggregator/commons/utilities/src/main/java/org/openrepose/commons/utils/servlet/http/QualityFormatException.java, repose-aggregator/commons/utilities/src/main/scala/org/openrepose/commons/utils/servlet/http/HttpServletRequestWrapper.scala, repose-aggregator/commons/utilities/src/test/scala/org/openrepose/commons/utils/servlet/http/HttpServletRequestWrapperTest.scala
This PR includes a couple of suggestions I have. Sorry about the formatting mess. If you want to format your branch, I'll rebase off of it to clean this PR up. I believe using IntelliJ's auto-formatting is the right call since it provides consistency.
One of the big changes here is to use Scala TreeMap and TreeSet so that we can provide a case-insensitive ordering. The prevents the need to wrap header names. The idea was first implemented in api-checker, as you can see at: https://github.com/rackerlabs/api-checker/blob/master/core/src/main/scala/com/rackspace/com/papi/components/checker/util/HeaderMap.scala
I also reworked getSplittablePreferredHeader. In my opinion, it's much cleaner now. If you like it, we could do the same for getPreferredHeader.
I also added a test to show that …
=> Ordering Rather Than Wrapping, Auto-Formatting, Test

repose-aggregator/installation/bash/repose-test_system-model.cfg.patch, repose-aggregator/installation/configs/core/system-model.cfg.xml
Since the `openrepose.org` page was moved to GitHub pages over a year ago, the default installation and original test instructions would not work out of the box. The original test instructions, which made sense, assume the `openrepose.org` endpoint will return a redirect to `www.openrepose.org`. When the main page was moved to GitHub pages the redirect was flipped, that is `www.openrepose.org` redirected to `openrepose.org`. This in and of itself is not bad, but it is not behavior that is consistent with industry standards. This part was corrected on the the web page and DNS a couple of weeks ago.
Additionally there are also some games that GitHub pages plays that causes the following for the first several requests from a non-browser call:
```
$ curl -i openrepose.org
HTTP/1.1 302 Found …
```
=> Updated the destination hostname and removed the rate-limiting filter from the default system-model.cfg.xml

repose-aggregator/components/filters/destination-router/src/test/java/org/openrepose/filters/destinationrouter/RoutingTaggerTest.java
There was an unused object creation and a duplicated String that was already a constant.
=> Cleaned up the RoutingTaggerTest a bit.

repose-aggregator/commons/utilities/src/main/java/org/openrepose/commons/utils/servlet/http/HeaderInteractor.java, repose-aggregator/commons/utilities/src/main/scala/org/openrepose/commons/utils/servlet/http/HttpServletRequestWrapper.scala, repose-aggregator/commons/utilities/src/test/scala/org/openrepose/commons/utils/servlet/http/HttpServletRequestWrapperTest.scala, repose-aggregator/components/filters/rate-limiting/src/main/java/org/openrepose/filters/ratelimiting/RateLimitingServiceHelper.java, repose-aggregator/components/filters/rate-limiting/src/test/groovy/org/openrepose/filters/ratelimiting/RateLimitingServiceHelperTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/common/log4j2-test.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/headertranslation/common/header-translation.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/ratelimiting/ratelimitbyroletest/header-translation.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/ratelimiting/ratelimitbyroletest/openstack-identity-v3.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/ratelimiting/ratelimitbyroletest/rate-limiting.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/ratelimiting/ratelimitbyroletest/system-model.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/ratelimiting/RateLimitingByRolesTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/framework/mocks/MockIdentityV3Service.groovy
This fixes the bug in rate limiting where the header values for x-pp-groups were not being parsed -- the entire header line was used.
=> REP-2388 Handle multiple x-pp-groups values on one line

repose-aggregator/core/core-lib/src/main/java/org/openrepose/powerfilter/PowerFilter.java, repose-aggregator/core/core-lib/src/test/scala/org/openrepose/core/spring/CoreSpringProviderTest.scala, repose-aggregator/core/core-service-api/src/main/resources/META-INF/schema/system-model/system-model.xsd, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/core/tracing/rewritetransid/system-model.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/core/tracing/RewriteTracingHeaderTest.groovy
Added "rewrite-tracing-header" attribute to the system model as a boolean to allow users to configure Repose to ignore inbound transaction ids but still have tracing enabled.  The default value is false.
Update was made to PowerFilter.java to remove the "X-Trans-Id" header when the "rewrite-tracing-header" attribute is set to true.  PowerFilter.java does not have an existing unit test, and the class is complex enough that adding a unit test would take a significant amount of time.
I added a functional test (RewriteTracingHeaderTest.groovy) to verify that the request and the response get a new "X-Trans-Id" header whether or not one was passed into the original request.  I also ran the TracingHeaderDisabledTest to regression test the original behavior.
I also added a unit test to verify …
=> Rep 2355 rewrite trans id header

repose-aggregator/components/filters/client-auth/src/main/java/org/openrepose/filters/clientauth/ClientAuthenticationFilter.java, repose-aggregator/components/filters/client-auth/src/main/java/org/openrepose/filters/clientauth/ClientAuthenticationHandlerFactory.java, repose-aggregator/components/filters/client-auth/src/main/java/org/openrepose/filters/clientauth/atomfeed/AuthFeedReader.java, repose-aggregator/components/filters/client-auth/src/main/java/org/openrepose/filters/clientauth/atomfeed/FeedCacheInvalidator.java, repose-aggregator/components/filters/client-auth/src/main/java/org/openrepose/filters/clientauth/atomfeed/FeedListenerManager.java, repose-aggregator/components/filters/client-auth/src/main/java/org/openrepose/filters/clientauth/atomfeed/sax/SaxAuthFeedReader.java, repose-aggregator/components/filters/client-auth/src/test/java/org/openrepose/filters/clientauth/atomfeed/AuthFeedListenerTest.java, repose-aggregator/components/filters/client-auth/src/test/java/org/openrepose/filters/clientauth/atomfeed/FeedCacheInvalidatorTest.java, repose-aggregator/components/filters/client-auth/src/test/java/org/openrepose/filters/clientauth/atomfeed/FeedListenerManagerTest.java, repose-aggregator/components/filters/client-auth/src/test/java/org/openrepose/filters/clientauth/atomfeed/sax/SaxAuthFeedReaderTest.java, repose-aggregator/components/filters/client-auth/src/test/resources/log4j2-test.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/clientauthn/cache/InvalidateCacheUsingAtomFeedTest.groovy
A x-trans-id is logged and added as a header for each invalidation request.
=> Rep 2357: Generate and add a x-trans-id to feed invalidation requests

repose-aggregator/components/filters/content-type-stripper/src/main/scala/org/openrepose/filters/contenttypestripper/ContentTypeStripperFilter.scala, repose-aggregator/components/filters/derp/src/main/scala/org/openrepose/filters/derp/DerpFilter.scala, repose-aggregator/core/core-lib/src/main/java/org/openrepose/powerfilter/filtercontext/FilterContextFactory.java, repose-aggregator/core/core-lib/src/test/scala/org/openrepose/powerfilter/filtercontext/FilterContextFactoryTest.scala, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/contenttypestripper/ContentTypeStripperTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/derp/DerpResponseMessagingTest.groovy
I removed the Named annotation from DerpFilter and verified that the functional tests DerpAndClientAuthNDelegable.groovy, DerpAndDelegableQuality.groovy, and DerpResponseMessagingTest.groovy failed.  I also updated FilterContextFactoryTest.scala to remove the existing unit test that verifies that an unannotated filter should cause an exception to be thrown and added a test to verify it won't.  The unit and functional tests failed in the correct way.
I updated FilterContextFactory.java to first check if the Spring application context had any beans for the configured class, and if not then it'll try creating a new instance of that class using reflection.  I removed the exception handling for the case where we try to get the bean from the application context and it doesn't exist (since we …
=> Added support for filters that don't need spring annotations

repose-aggregator/core/web-application/pom.xml
Also put the Spring dependencies in the same order as the Valve POM to make for easier comparisons.
=> Updated the WAR pom to include the missing Log4J 2.x jars and to exclude the old commons-logging.

repose-aggregator/commons/utilities/src/main/java/org/openrepose/commons/utils/servlet/http/MutableHttpServletResponse.java, repose-aggregator/components/filters/derp/src/main/scala/org/openrepose/filters/derp/DerpFilter.scala, repose-aggregator/components/filters/derp/src/test/scala/org/openrepose/filters/derp/DerpFilterTest.scala, repose-aggregator/core/core-lib/src/main/java/org/openrepose/powerfilter/PowerFilterChain.java, repose-aggregator/core/core-lib/src/main/java/org/openrepose/powerfilter/RequestTracer.java, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/herp/apivalidatormultimatch/response-messaging.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/herp/wderpandrms/response-messaging.cfg.xml
If the initial `MutableHttpServletResponse` wrapper was re-wrapped by another type (e.g. `CheckerServletResponse`), then the delegation message set in the `DerpFilter` was never propagated to the `ResponseMessageHandler`.
The `ResponseMessageHandler` is expecting to retrieve the message from `MutableHttpServletResponse.getMessage()`.
* https://github.com/rackerlabs/repose/blob/master/repose-aggregator/commons/utilities/src/main/java/org/openrepose/commons/utils/logging/apache/format/stock/ResponseMessageHandler.java#L40
This message is set using the `HttpServletResponse.sendError(int, String)` on a `MutableHttpServletResponse`. The delegation message was originally only being set in the `DerpFilter` using `HttpServletResponse.getWriter.write(String)`.
* …
=> REP-2494 DerpFilter delegation message not making it to ResponseMessageHandler.

repose-aggregator/components/filters/client-auth/src/main/java/org/openrepose/filters/clientauth/openstack/OpenStackAuthenticationHandler.java, repose-aggregator/components/filters/client-auth/src/test/java/org/openrepose/filters/clientauth/openstack/OpenStackAuthenticationHandlerTest.java
I updated Client Auth to be case sensitive when testing for Tenant ID equality.
Jenny added a functional test to verify that Client Auth is case sensitive when testing for Tenant ID equality.  Before my update, the functional test failed as expected.  After the update, the test passed.  Unit tests also correctly failed before the update and passed after the update.
Keystone v3 doesn't need to be updated:
https://github.com/rackerlabs/repose/blob/master/repose-aggregator/components/filters/openstack-identity-v3/src/main/scala/org/openrepose/filters/openstackidentityv3/OpenStackIdentityV3Handler.scala#L325
=> Rep 2521 tenant id case sensitive

repose-aggregator/commons/utilities/src/main/java/org/openrepose/commons/utils/logging/apache/HttpLogFormatter.java, repose-aggregator/commons/utilities/src/main/java/org/openrepose/commons/utils/logging/apache/LogArgumentGroupExtractor.java, repose-aggregator/commons/utilities/src/main/java/org/openrepose/commons/utils/logging/apache/format/stock/TimeReceivedHandler.java, repose-aggregator/commons/utilities/src/test/java/org/openrepose/commons/utils/logging/apache/HttpLogFormatterTest.java, repose-aggregator/core/core-lib/src/test/scala/org/openrepose/core/spring/CoreSpringProviderTest.scala, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/slf4jhttplogging/customdateformat/slf4j-http-logging.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/slf4jhttplogging/invaliddateformat/slf4j-http-logging.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/slf4jlogging/Slf4jHttpLoggingCustomDateFormatTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/slf4jlogging/Slf4jHttpLoggingInvalidDateFormatTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/slf4jlogging/Slf4jHttpLoggingTest.groovy
The slf4j http logging string already had support for adding a {} between the %t characters, so I added support for putting a date format in there.  Not specifying a format defaults to the current behavior.  A timebomb was added to change the default format in version 8.  Details about the formatting are documented here (under %{format}t):
https://repose.atlassian.net/wiki/display/REPOSE/SLF4J+HTTP+Logging+filter#SLF4JHTTPLoggingfilter-Whatislogged
Functional tests were added to confirm the existing default behavior and to confirm the custom date format behavior.
=> Rep 2379 logging timestamp formatting

repose-aggregator/services/service-client/impl/src/main/java/org/openrepose/core/services/serviceclient/akka/impl/AkkaServiceClientImpl.java
Cleaned up the `AkkaServiceClientImpl` `.get()` and `.post()` methods to more clearly show that a `ServiceClientResponse` is returned or a checked `AkkaServiceClientException` is thrown, but `NULL` is never returned.
=> This was found while working on REP-2548 even though it isn't directly related to it.

repose-aggregator/components/filters/client-auth/src/main/java/org/openrepose/filters/clientauth/common/AuthenticationHandler.java, repose-aggregator/components/filters/client-auth/src/main/java/org/openrepose/filters/clientauth/common/Configurables.java, repose-aggregator/components/filters/client-auth/src/main/java/org/openrepose/filters/clientauth/openstack/OpenStackAuthenticationHandler.java, repose-aggregator/components/filters/client-auth/src/main/java/org/openrepose/filters/clientauth/openstack/OpenStackAuthenticationHeaderManager.java, repose-aggregator/components/filters/client-auth/src/main/resources/META-INF/schema/config/openstack-ids-auth/openstack-ids-auth.xsd, repose-aggregator/components/filters/client-auth/src/test/groovy/org/openrepose/filters/clientauth/common/AuthenticationHandlerTest.groovy, repose-aggregator/components/filters/client-auth/src/test/groovy/org/openrepose/filters/clientauth/openstack/OpenStackAuthenticationHeaderManagerGroovyTest.groovy, repose-aggregator/components/filters/client-auth/src/test/java/org/openrepose/filters/clientauth/openstack/OpenStackAuthenticationHeaderManagerTest.java, repose-aggregator/components/filters/keystone-v2/src/main/scala/org/openrepose/filters/keystonev2/KeystoneV2Filter.scala, repose-aggregator/components/filters/keystone-v2/src/test/scala/org/openrepose/filters/keystonev2/KeystoneV2FilterTest.scala, repose-aggregator/external/service-clients/auth/src/main/java/org/openrepose/common/auth/AuthToken.java, repose-aggregator/external/service-clients/auth/src/main/java/org/openrepose/common/auth/openstack/OpenStackToken.java, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/clientauthn/removetenant/tenantednondelegable/client-auth-n.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/keystonev2/removetenant/tenantednondelegable/keystone-v2.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/valkyrie/client-auth-n.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/clientauthn/tenantvalidation/NonTenantedAuthTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/clientauthn/tenantvalidation/TenantedNonDelegableTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/keystonev2/KeystoneV2BasicTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/keystonev2/nogroups/TenantedNonDelegableNoGroupsTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/keystonev2/tenantvalidation/BypassTenantRolesWQualityTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/keystonev2/tenantvalidation/ClientAuthNRemoveTenantTenantedDelegableTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/keystonev2/tenantvalidation/TenantedNonDelegableTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/valkyrie/BasicValkyrieTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/framework/mocks/MockIdentityService.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/framework/mocks/MockIdentityV2Service.groovy
Note that there are no changes to the Identity v3 filters. That filter already appears to meet the acceptance criteria of the story.
=> REP-2670 Remove Reliance on Default Tenant ID

repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/core/intrafilterlogging/tracingmultigroups/system-model.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/core/intrafilterlogging/IntraFilterLoggingMultipleGroupsTest.groovy
Needed to grab the lines as it was going into the echo filter, coming
out of the translation filter, not going into the translation filter. We
don't see the results of a filter unless it's getting logged going INTO
another filter.
This should be applied to #1388 to get the build passing.
=> Modifications to the test

repose-aggregator/components/filters/valkyrie-authorization/src/main/scala/org/openrepose/filters/valkyrieauthorization/ValkyrieAuthorizationFilter.scala, repose-aggregator/components/filters/valkyrie-authorization/src/test/scala/org/openrepose/filters/valkyrieauthorization/ValkyrieAuthorizationFilterTest.scala, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/valkyrie/translatepermissionstoroles/devicelevel/validator.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/valkyrie/DeviceLevelPermissionToRolesTest.groovy
In the Valkyrie filter, when configured to translate account permissions and given a request with an "X-Device-Id" header, instead of just verifying the Device ID permission allows the request to go through, the Device ID permission will also be added to the list of permission roles which in turn get added as values to the X-Roles header.  This includes the Device ID permissions "view_product", "edit_product", and "admin_product".  The "account_admin" case is already handled as it will already be in the list of role permissions.
A unit test covering the combination of being configured to translate account permissions and handling a request with an "X-Device-Id" header did not already exist, so I added one.
=> Added device level permissions to X-Roles headers

repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/herp/apivalidatormultimatch/wauthnpreference/wbasicauth/rackspace-identity-basic-auth.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/herp/apivalidatormultimatch/wauthnpreference/wbasicauth/system-model.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/keystonev2/atom/keystone-v2.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/services/atomfeedservice/system-model.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/herp/BasicAuthHerpDerpRMSMultiMatchAuthTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/identitybasicauth/BasicAuthTest.groovy
I tried to replicate Shinta's basic auth issue as claim invalid large key response with 500 but I couldn't. However, it's good to have these tests in place.
- verified basicauth authentication with invalid large key - 401 
- verified basicauth authentication with invalid large key delegation higher quality through (basicauth, authn, api-validator, herp, derp) - 401 with appropriate delegating error message.
=> Update basic auth tests

repose-aggregator/installation/deb/repose-cli-utils/src/deb/control/control, repose-aggregator/installation/deb/repose-extensions-filter-bundle/src/deb/control/control, repose-aggregator/installation/deb/repose-filter-bundle/src/deb/control/control
It adds the additional incorrect package name to the possible dependencies list.
=> Here is an interim solution that will fix the Debian WAR installations.

repose-aggregator/components/filters/valkyrie-authorization/pom.xml, repose-aggregator/components/filters/valkyrie-authorization/src/main/resources/META-INF/schema/config/valkyrie-authorization.xsd, repose-aggregator/components/filters/valkyrie-authorization/src/main/resources/META-INF/schema/examples/valkyrie-authorization.cfg.xml, repose-aggregator/components/filters/valkyrie-authorization/src/main/scala/org/openrepose/filters/valkyrieauthorization/ValkyrieAuthorizationFilter.scala, repose-aggregator/components/filters/valkyrie-authorization/src/test/scala/org/openrepose/filters/valkyrieauthorization/ValkyrieAuthorizationFilterTest.scala, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/valkyrie/accountadmin/http-connection-pool.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/valkyrie/accountadmin/valkyrie-authorization.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/valkyrie/collectionresources/valkyrie-authorization.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/valkyrie/AccountAdminTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/framework/mocks/MockValkyrie.groovy
This enhancement provided a backwards compatible way to make the Valkyrie filter's config able to support the new expected default behavior. Part of this behavior required adding a second call to Valkyrie in order to obtain the Account Device Inventory when the original Direct Permissions by Contact call returns a role of 'account_admin'.
=> REP-2972 Valkyrie account_admin enhancement.

repose-aggregator/components/filters/filter-bundle/pom.xml, repose-aggregator/components/filters/filter-bundle/src/main/application/WEB-INF/web-fragment.xml, repose-aggregator/components/filters/pom.xml, repose-aggregator/components/filters/url-extractor-to-header/pom.xml, repose-aggregator/components/filters/url-extractor-to-header/src/main/resources/META-INF/schema/config/bindings.xjb, repose-aggregator/components/filters/url-extractor-to-header/src/main/resources/META-INF/schema/config/url-extractor-to-header.xsd, repose-aggregator/components/filters/url-extractor-to-header/src/main/resources/META-INF/schema/examples/url-extractor-to-header.cfg.xml, repose-aggregator/components/filters/url-extractor-to-header/src/main/scala/org/openrepose/filters/urlextractortoheader/UrlExtractorToHeaderFilter.scala, repose-aggregator/components/filters/url-extractor-to-header/src/test/scala/org/openrepose/filters/urlextractortoheader/UrlExtractorToHeaderFilterTest.scala, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/urlextractortoheader/system-model.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/urlextractortoheader/url-extractor-to-header.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/urlextractortoheader/wvalkyrie/client-auth-n.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/urlextractortoheader/wvalkyrie/system-model.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/urlextractortoheader/wvalkyrie/valkyrie-authorization.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/urlextractortoheader/UrlExtractorToHeaderTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/urlextractortoheader/UrlExtractorToHeaderWValkyrieTest.groovy
Added new filter that let's you extract part of the URL and put it in a header.  The header name is configurable, the header value is the first group in the configured regex, and a default value can be specified (or left out if the header shouldn't added) when the regex doesn't match the URL.
=> Rep 2128 url extraction to header filter

repose-aggregator/extensions/api-validator/src/main/java/org/openrepose/filters/apivalidator/ApiValidatorHandler.java, repose-aggregator/extensions/api-validator/src/test/java/org/openrepose/filters/apivalidator/ApiValidatorHandlerTest.java
This is what came out of the Ninja task investigation for:
* https://repose.atlassian.net/browse/REP-3177
=> REP-3199 API-Validator filter is not splitting the X-Roles header.

repose-aggregator/components/filters/rate-limiting/src/test/java/org/openrepose/filters/ratelimiting/RateLimitingHandlerTest.java, repose-aggregator/components/filters/versioning/src/test/java/org/openrepose/filters/versioning/VersioningHandlerTest.java, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/core/classloader/ClassLoaderTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/experimental/servletContract/ServletContractFilterTest.groovy
Kicking the can like last time:
https://github.com/rackerlabs/repose/commit/57a7bfc4b038ee6e4a1c39ebd9047df6b017ce19
I went with April 4 because April 1 is a Friday, and I just know it'll mess up a release or something.
=> Moved time bombs to April

repose-aggregator/components/filters/add-header/src/main/resources/META-INF/schema/config/add-header.xsd, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/addheader/noheader/add-header.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/addheader/requestonly/add-header.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/addheader/responseonly/add-header.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/addheader/AddHeaderOverwriteTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/addheader/AddHeaderRequestOnlyTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/addheader/AddHeaderResponseOnlyTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/addheader/AddHeaderTest.groovy
Previously the Add Header filter required you to configure headers for both the request and the response.  I updated the XSD to allow a user to configure just one of them if they wanted to.  The code already handles having just one of them configured.
There's an existing functional test with both configured.  I added two additional tests with just the request and just the response to ensure it worked.
=> REP 3175 Add Header Filter config update

repose-aggregator/pom.xml
To address the following issue:
https://github.com/jacoco/jacoco/issues/74
=> Upgrading JaCoCo to fix Java8 compatibility

repose-aggregator/components/filters/keystone-v2/src/main/scala/org/openrepose/filters/keystonev2/KeystoneV2Filter.scala, repose-aggregator/components/filters/keystone-v2/src/test/scala/org/openrepose/filters/keystonev2/IdentityResponses.scala, repose-aggregator/components/filters/keystone-v2/src/test/scala/org/openrepose/filters/keystonev2/KeystoneV2FilterTest.scala, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/keystonev2/KeystoneV2BasicTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/keystonev2/admintoken/IdentityAdminTokenTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/keystonev2/akkatimeout/HttpConnTimeoutGreaterThan50SecTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/keystonev2/akkatimeout/NoPoolIdAkkaTimeoutUsingDefaultTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/keystonev2/nogroups/TenantedNonDelegableNoGroupsTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/keystonev2/selfvalidation/KeystoneV2SelfValidationTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/keystonev2/tenantvalidation/BypassTenantRolesWQualityTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/keystonev2/tenantvalidation/ClientAuthNRemoveTenantTenantedDelegableTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/keystonev2/tenantvalidation/ClientAuthNTenantedDelegableTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/keystonev2/tenantvalidation/TenantedNonDelegableTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/valkyrie/CullingBypassValkyrieAuthorizationTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/valkyrie/GetDeviceBypassValkyrieAuthorizationTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/valkyrie/TranslateRolesBypassValkyrieTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/framework/mocks/MockIdentityV2Service.groovy
The `mockAkkaServiceClient.validate()` call in `KeystoneV2FilterTest` was moved from the `after()` method into each test. This was done so that all the tests would run and not just abort on the first failure with no indication of the why it had stopped or even which test had caused the issue.
=> REP-3204 - Fix Keystone v2^2 Get Groups call to Keystone/Identity

repose-aggregator/components/filters/valkyrie-authorization/src/main/scala/org/openrepose/filters/valkyrieauthorization/ValkyrieAuthorizationFilter.scala, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/ratelimiting/globalratelimit/rate-limiting.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/ratelimiting/GlobalRateLimiting2NodesTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/ratelimiting/GlobalRateLimitingTest.groovy, repose-aggregator/services/rate-limiting-service/src/main/java/org/openrepose/core/services/ratelimit/RateLimitingServiceImpl.java, repose-aggregator/services/rate-limiting-service/src/test/groovy/org/openrepose/core/services/ratelimit/RateLimitingServiceImplTest.groovy
I also brought in the minor consistency update to the Valkyrie Authorization filter so it would behave exactly like the Rate Limiting filter in the future.
=> REP-3504 Rate Limiting default HTTP Methods fix.

repose-aggregator/commons/commons-utilities/src/main/java/org/openrepose/commons/utils/logging/apache/format/stock/TimeReceivedHandler.java, repose-aggregator/commons/commons-utilities/src/test/java/org/openrepose/commons/utils/logging/apache/HttpLogFormatterTest.java, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/slf4jhttplogging/customdateformat/slf4j-http-logging.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/slf4jlogging/Slf4jHttpLoggingCustomDateFormatTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/slf4jlogging/Slf4jHttpLoggingTest.groovy
I updated the default time format used by the SLF4J logging filter from "dd-MM-yyyy-HH:mm:ss.SSS" to "yyyy-MM-dd HH:mm:ss".  I also updated the functional tests to use the new default time, and I updated the custom time format test to use the old default just for fun.
=> REP-3168 - Update to default time format in SLF4J logging

repose-aggregator/functional-tests/spock-functional-test/pom.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/core/embedded/EmbeddedTomcatProxyTest.groovy, repose-aggregator/functional-tests/tomcat-support/pom.xml, repose-aggregator/functional-tests/tomcat-support/src/main/java/org/openrepose/commons/utils/test/tomcat/ReposeTomcatContainer.java
I updated three spots that were using the mocks-util module.  Two were easy to replace.  The third involved using XmlSlurper to do some unmarshalling.  There's still a dependency in mocks-servlet on mocks-util, but that's going away I hear.  Of note, EmbeddedTomcatProxyTest uses the WAR generated by mocks-servlet, so additional updates will be needed in EmbeddedTomcatProxyTest before mocks-servlet and thus mocks-util can be removed.
=> Removing dependencies on mocks-util module

repose-aggregator/components/filters/simple-rbac-filter/pom.xml, repose-aggregator/components/filters/simple-rbac-filter/src/main/scala/org/openrepose/filters/simplerbac/SimpleRbacFilter.scala
I removed the old wrapper usage in Simple RBAC.  I don't see why they were wrapped in the first place, so I didn't replace them with the new wrappers.  I also removed the core-lib dependency and had to add the jcl-over-slf4j dependency for the tests.
The gradle build worked without any updates.
=> REP-3281 - Simple RBAC wrapper updates

repose-aggregator/components/filters/keystone-v2-filter/src/main/scala/org/openrepose/filters/keystonev2/KeystoneV2Filter.scala, repose-aggregator/components/filters/keystone-v2-filter/src/test/scala/org/openrepose/filters/keystonev2/KeystoneV2FilterPrepTest.scala, repose-aggregator/components/filters/keystone-v2-filter/src/test/scala/org/openrepose/filters/keystonev2/KeystoneV2FilterTest.scala, repose-aggregator/components/services/phone-home-service/src/main/scala/org/openrepose/core/services/phonehome/PhoneHomeService.scala, repose-aggregator/components/services/phone-home-service/src/test/scala/org/openrepose/core/services/phonehome/PhoneHomeServiceTest.scala, repose-aggregator/core/core-lib/src/main/java/org/openrepose/powerfilter/PowerFilter.java, repose-aggregator/core/core-lib/src/test/groovy/org/openrepose/nodeservice/httpcomponent/RequestProxyServiceImplTest.groovy, repose-aggregator/core/core-service-api/src/main/resources/META-INF/schema/system-model/system-model.xsd, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/core/tracing/rewritetransid/rewritefalse/system-model.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/core/tracing/rewritetransid/system-model.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/core/tracing/RewriteTracingHeaderTest.groovy
I updated the tracing header config in the system model from being a pair of attributes to an element with those two attributes.  I also updated code to use the new generated source.
Previously, the tracing header attribute was set to true by default (i.e. if it wasn't explicitly configured, it would be turned on).  With these updates, if the element is not specified, it will default to being turned on.  If the element is specified, but the attribute is not, it will still default to true.  As before, the only way to turn it off is to specify the attribute with a value of false.  I was going to make the attribute required (because if you already have the element then why not?), but I kept it optional in case all you wanted to do was change the rewrite behavior.
The rewrite attribute pretty …
=> REP-3167 - Tracing Header updates

repose-aggregator/components/filters/tightly-coupled-filter/src/main/java/org/openrepose/experimental/filters/servletcontract/TightlyCoupledFilter.java, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/experimental/tightlyCoupled/TighlyCoupledandOtherFilterTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/experimental/tightlyCoupled/TightlyCoupledFilterTest.groovy
I updated the Tightly Coupled filter to use the new wrappers.  I removed the unnecessary request wrapping and a couple of odd logging statements (like asking the request for the response content type).  I also removed the "hasBody" check on the response as the new wrapper doesn't support that (and as I understand it the old wrapper barely did anyway).
I also had to set the Content-Length for the whole response to be read by Deproxy.
Also :panda_face: s.
=> REP-3491 - Tightly Coupled filter wrapper updates

repose-aggregator/artifacts/valve/src/main/scala/org/openrepose/valve/ReposeJettyServer.scala, repose-aggregator/core/core-service-api/src/main/resources/META-INF/schema/container/container-configuration.xsd
I updated the XSD to default to false (which is just for show), and I updated the code to specifically set it to disabled (false) if the config element is null (since behind the covers the default is true).
=> REP-3317 - Defaulted TLS Renegotiation to false

repose-aggregator/components/filters/api-validator-filter/build.gradle, repose-aggregator/components/filters/api-validator-filter/pom.xml, repose-aggregator/components/filters/api-validator-filter/src/main/java/org/openrepose/filters/apivalidator/ApiValidatorFilter.java, repose-aggregator/components/filters/api-validator-filter/src/main/java/org/openrepose/filters/apivalidator/ApiValidatorHandler.java, repose-aggregator/components/filters/api-validator-filter/src/main/java/org/openrepose/filters/apivalidator/ApiValidatorHandlerFactory.java, repose-aggregator/components/filters/api-validator-filter/src/main/java/org/openrepose/filters/apivalidator/ValidatorConfigurator.java, repose-aggregator/components/filters/api-validator-filter/src/main/java/org/openrepose/filters/apivalidator/ValidatorInfo.java, repose-aggregator/components/filters/api-validator-filter/src/main/resources/META-INF/schema/config/validator-configuration.xsd, repose-aggregator/components/filters/api-validator-filter/src/test/groovy/org/openrepose/filters/apivalidator/ApiValidatorHandlerFactoryTest.groovy, repose-aggregator/components/filters/api-validator-filter/src/test/java/org/openrepose/filters/apivalidator/ApiValidatorHandlerTest.java, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/apivalidator/ApiValidatorJMXTest.groovy
Our typical update pattern wasn't going to work for this filter, so I kept the existing structure and just removed all of the FilterDirector/FilterLogicHandlerDelegate/old wrapper stuff.  I also cleaned up the code a bit (mostly renaming stuff) since I had the context in my brain.
=> REP-3280 - API Validation wrapper updates

repose-aggregator/components/filters/header-translation-filter/src/main/resources/META-INF/schema/config/header-translation.xsd, repose-aggregator/components/filters/header-translation-filter/src/main/scala/org/openrepose/filters/headertranslation/HeaderTranslationFilter.scala, repose-aggregator/components/filters/header-translation-filter/src/test/scala/org/openrepose/filters/headertranslation/HeaderTranslationFilterTest.scala, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/headertranslation/wquality/header-translation.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/headertranslation/HeaderTranslationWQualityTest.groovy
I added "quality" and "splittable" attributes to the header config item for the Header Translation filter.  The filter now supports adding a quality parameter to the headers it creates (while not carrying over any quality parameter that was on the original header value).  If no "quality" attribute is specified, none is added (i.e. the quality parameter on the original header will be used if it exists).
In case the header is splittable, a config item was added to have the filter split the header values before applying a new quality when creating the new headers.
=> REP-3629 - Header Translation - configure quality

repose-aggregator/components/filters/rackspace-identity-basic-auth-filter/src/main/resources/META-INF/schema/config/rackspace-identity-basic-auth.xsd, repose-aggregator/components/filters/rackspace-identity-basic-auth-filter/src/main/resources/META-INF/schema/examples/rackspace-identity-basic-auth.cfg.xml, repose-aggregator/components/filters/rackspace-identity-basic-auth-filter/src/main/scala/org/openrepose/filters/rackspaceidentitybasicauth/RackspaceIdentityBasicAuthFilter.scala, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/core/intrafilterlogging/rackspace-identity-basic-auth.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/herp/apivalidatormultimatch/wauthpreference/wbasicauth/rackspace-identity-basic-auth.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/identitybasicauth/akkatimeout/diffpool/rackspace-identity-basic-auth.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/identitybasicauth/akkatimeout/nopool/rackspace-identity-basic-auth.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/identitybasicauth/akkatimeout/rackspace-identity-basic-auth.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/identitybasicauth/cache/rackspace-identity-basic-auth.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/identitybasicauth/delegating/rackspace-identity-basic-auth.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/identitybasicauth/rackspace-identity-basic-auth.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/identitybasicauth/wpassword/rackspace-identity-basic-auth.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/framework/mocks/MockIdentityV2Service.groovy
Only the rackspace-identity-basic-auth filter needed to be updated. All of the others expected just scheme, host, and port -- not the path.
Before this gets merged, the task to talk to users to make sure we aren't breaking their proxies should be completed.
=> REP-3393 Make our identity URLs in config consistent

repose-aggregator/components/filters/rate-limiting-filter/src/test/java/org/openrepose/filters/ratelimiting/RateLimitingHandlerTest.java, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/core/classloader/ClassLoaderTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/experimental/servletContract/ServletContractFilterTest.groovy
I moved the time bombs for:
- RateLimitingHandlerTest
- ClassLoaderTest
Time bombs no longer needed (and thus removed on this branch):
- ServletContractFilterTest
Time bombs no longer existed for:
- VersioningHandlerTest
=> Moved time bombs (repose-8-staging branch)

repose-aggregator/components/filters/rate-limiting/src/test/java/org/openrepose/filters/ratelimiting/RateLimitingHandlerTest.java, repose-aggregator/components/filters/versioning/src/test/java/org/openrepose/filters/versioning/VersioningHandlerTest.java, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/core/classloader/ClassLoaderTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/experimental/servletContract/ServletContractFilterTest.groovy
Moved time bombs to July 5 (Tuesday).
Of note, one of these won't exist in Repose 8 and another one is fixed, but I updated anyway to get master working.
=> Moved time bombs to July

repose-aggregator/commons/commons-utilities/src/main/java/org/openrepose/commons/utils/io/buffer/CyclicByteBuffer.java, repose-aggregator/commons/commons-utilities/src/main/java/org/openrepose/commons/utils/servlet/http/MutableHttpServletResponse.java, repose-aggregator/commons/commons-utilities/src/test/java/org/openrepose/commons/utils/servlet/http/MutableHttpServletResponseTest.java, repose-aggregator/core/repose-core/src/main/java/org/openrepose/powerfilter/PowerFilter.java, repose-aggregator/core/repose-core/src/main/java/org/openrepose/powerfilter/PowerFilterChain.java, repose-aggregator/core/repose-core/src/main/java/org/openrepose/powerfilter/intrafilterLogging/RequestLog.java, repose-aggregator/core/repose-core/src/main/java/org/openrepose/powerfilter/intrafilterLogging/ResponseLog.java, repose-aggregator/core/repose-core/src/test/scala/org/openrepose/powerfilter/intrafilterLogging/RequestLogTest.scala, repose-aggregator/core/repose-core/src/test/scala/org/openrepose/powerfilter/intrafilterLogging/ResponseLogTest.scala, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/core/intrafilterlogging/header-normalization.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/core/intrafilterlogging/responsebody/system-model.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/core/intrafilterlogging/simple-rbac.cfg.xml, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/core/intrafilterlogging/IntraFilterLoggingRequestResponseBodyTest.groovy, repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/core/intrafilterlogging/IntraFilterLoggingResponseBodyTest.groovy
Instead of wrapping the request and response with the old mutable wrappers in the PowerFilterChain.doReposeFilter() method, I use what's passed in when intrafilter logging is turned off and wrap it using the new wrappers when it's set to trace.
I also check if the InputStream in the request supports mark/reset, and if it doesn't, I copy the data over to an InputStream that does (and use that when wrapping the request).
For the response, I wrap it using READONLY mode on the body so I can read the OutputStream.
I'm not a huge fan of the maybeWrapped stuff, but I expect the PowerFilterChain to be updated soon anyway.
I added a new functional test to verify:
- the origin service receives the request body sent from the client
- the client receives the response body sent from the origin service …
=> REP-3573 - Intra-filter logging wrapper updates

repose-aggregator/components/filters/uri-normalization-filter/src/main/scala/org/openrepose/filters/urinormalization/UriNormalizationFilter.scala, repose-aggregator/components/filters/uri-normalization-filter/src/test/scala/org/openrepose/filters/urinormalization/UriNormalizationFilterTest.scala
I added a unit test that consistently triggered the ordering issue when loading the URI Norm config, and I changed the scala HashMap to a scala LinkedHashMap in the filter which preserves the ordering of the config.
=> REP-3667 - URI Normalization config ordering

repose-aggregator/artifacts/experimental-filter-bundle/build.gradle, repose-aggregator/artifacts/extensions-filter-bundle/build.gradle, repose-aggregator/artifacts/filter-bundle/build.gradle, repose-aggregator/artifacts/src/config/scripts/preinst-rpm
The install script for the RPM installer was encoded to be in an XML file which it isn't anymore, so I fixed that.
Also, the filter RPMs wouldn't install because they were trying to create directories that already existed (from the valve RPM).  I updated the Gradle build to have the filter RPMs not try to create the directories.
I was able to install the valve RPM and the three filter RPMs in a Vagrant CentOS 7 VM.
=> REP-3311 - Fix RPM installer

repose-aggregator/components/filters/ip-user-filter/build.gradle, repose-aggregator/components/filters/ip-user-filter/src/main/scala/org/openrepose/filters/ipuser/IpUserFilter.scala, repose-aggregator/components/filters/ip-user-filter/src/test/scala/org/openrepose/filters/ipuser/IpUserFilterTest.scala, repose-aggregator/tests/functional-tests/src/test/groovy/features/filters/ipuser/IpUserTest.groovy, repose-aggregator/tests/functional-tests/src/test/groovy/features/filters/ipuser/IpUserWXForwardedForHeaderTest.groovy
The IP User filter now grabs the first splittable value of the X-Forwarded-For header to populate the x-pp-user header if it's available.  Otherwise, it'll use the remote IP address in the request (like it previously did).
There were some unit tests for this filter already, but none of them verified that the IP address was put into the X-PP-User header.  I added some unit tests to verify this and the behavior for when the X-Forwarded-For header is in the request.
=> REP-3838 - IP User filter should check X-Forwarded-For header first

repose-aggregator/artifacts/cli-utils/build.gradle, repose-aggregator/artifacts/experimental-filter-bundle/build.gradle, repose-aggregator/artifacts/extensions-filter-bundle/build.gradle, repose-aggregator/artifacts/filter-bundle/build.gradle, repose-aggregator/artifacts/valve/build.gradle, repose-aggregator/artifacts/web-application/build.gradle
This change allowed me to install packages on a local Ubuntu VM, whereas before dpkg was complaining about requiring a specific version of a virtual package.
=> Adding a hard version dependency for virtual packages

repose-aggregator/artifacts/valve/build.gradle
Since RPM platforms were the first to move to `systemd`, I think it is safe to remove System V support from them.
=> Removed all references to the RPM's requiring daemonize.

repose-aggregator/commons/commons-utilities/src/main/scala/org/openrepose/commons/utils/string/RegexStringOperators.scala, repose-aggregator/commons/commons-utilities/src/test/scala/org/openrepose/commons/utils/string/RegexStringOperatorsTest.scala, repose-aggregator/components/filters/body-patcher-filter/src/main/scala/org/openrepose/filters/bodypatcher/BodyPatcherFilter.scala, repose-aggregator/components/filters/uri-stripper-filter/src/main/scala/org/openrepose/filters/uristripper/UriStripperFilter.scala, repose-aggregator/components/filters/valkyrie-authorization-filter/src/main/scala/org/openrepose/filters/valkyrieauthorization/ValkyrieAuthorizationFilter.scala
These match two of Groovy's regex operators, `=~` and `==~`. There are two ways to use this utility in Scala -- import the implicit conversion, or mix-in the trait. Technically, I suppose you could also instantiate the extended class, or do some other shenanigans to pull the implicit conversion into scope, but the two aforementioned methods are probably preferred.
Note that this branched is branched off of REP-4010, because I wanted to update that code to use the new operator.
=> Extracting regex operators to a commons utility

repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/services/httpconnectionpool/chunkedfalse/http-connection-pool.cfg.xml, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/core/proxy/ContentLengthTest.groovy
Adding test (that is expected to fail) to prove that Repose sends the "Transfer-Encoding: chunked" header if the user sends it, regardless of the value of the "chunked-encoding" attribute of the default connection pool.
Story: https://repose.atlassian.net/browse/REP-4490
=> Chunked Encoding Test

repose-aggregator/components/filters/rackspace-auth-user-filter/src/main/scala/org/openrepose/filters/rackspaceauthuser/RackspaceAuthUserFilter.scala, repose-aggregator/components/filters/rackspace-auth-user-filter/src/main/scala/org/openrepose/filters/rackspaceauthuser/RackspaceAuthUserHandler.scala, repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/rackspaceauthuser/inputstream/compression.cfg.xml, repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/rackspaceauthuser/inputstream/rackspace-auth-user.cfg.xml, repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/rackspaceauthuser/inputstream/slf4j-http-logging.cfg.xml, repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/rackspaceauthuser/inputstream/system-model.cfg.xml, repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/rackspaceauthuser/inputstream/translation.cfg.xml, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/rackspaceauthuser/RackspaceAuthPayloads.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/rackspaceauthuser/inputstream/PrecededByCompressionFilterTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/rackspaceauthuser/inputstream/PrecededByContentTypeStripperFilterTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/rackspaceauthuser/inputstream/PrecededBySlf4jHttpLoggingFilterTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/rackspaceauthuser/inputstream/PrecededByTranslationFilterTest.groovy
I updated the code to use the new way of handling streams. That is the only change to the content of the merge that was modified. All of the tests were just stuck in the right spot.
Once this is merged, we can delete the release branch (`REP-4575_FixInputStreamAssumptions`).
=> REP-4582 Merging the 7.3.8.1 release into master

repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/core/classloader/ClassLoaderTest.groovy
The ClassLoaderTest was failing fairly often on the Jenkins nodes either on the second or third test.  The failures in the nightly builds and the ones I observed when running on slave4 all occurred when Deproxy was adding a new endpoint for the origin service.  The same port was being used across the three tests, so I updated the code to ensure that a new port would be used for the origin service and Repose for each test.
I verified in the logs that new ports are being used for each test run, and I verified that I could run the test 12 times on slave4 successfully.
Ninja task: https://repose.atlassian.net/browse/REP-4610
=> Fix ClassLoaderTest port issue

repose-aggregator/components/filters/cors-filter/src/main/scala/org/openrepose/filters/cors/CorsFilter.scala, repose-aggregator/components/filters/cors-filter/src/test/scala/org/openrepose/filters/cors/CorsFilterTest.scala, repose-aggregator/src/docs/asciidoc/filters/cors.adoc, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/cors/CorsFilterBasicTest.groovy
Update is to better handle the Access-Control-Request-Headers header on the request.  Previously, the value was taken from this header and put into the Access-Control-Allow-Headers header on the response without concern for whether or not there was more than one value.  This worked fine if the Access-Control-Request-Headers header was merged into one comma-separated value, but if the value was split, only the first value would be put in the Access-Control-Allow-Headers header.  This PR addresses the issue by calling `getSplittableHeaderScala` and adding a Access-Control-Allow-Headers header to the response for each value.
The CORS functional test was pretty confusing, so I cleaned it up before adding additional tests.
=> REP-3390 - CORS Access-Control-Request-Headers

repose-aggregator/components/filters/herp-filter/src/main/scala/org/openrepose/filters/herp/HerpFilter.scala, repose-aggregator/components/filters/herp-filter/src/test/scala/org/openrepose/filters/herp/HerpFilterTest.scala, repose-aggregator/components/filters/rackspace-auth-user-filter/src/main/scala/org/openrepose/filters/rackspaceauthuser/RackspaceAuthUserFilter.scala, repose-aggregator/components/filters/rackspace-auth-user-filter/src/test/scala/org/openrepose/filters/rackspaceauthuser/RackspaceAuthUserFilterTest.scala, repose-aggregator/src/docs/asciidoc/filters/herp.adoc, repose-aggregator/src/docs/asciidoc/filters/rackspace-auth-user.adoc, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/herp/HerpUserAccessEventFilterTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/rackspaceauthuser/RackspaceAuthPayloads.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/rackspaceauthuser/RackspaceAuthUserTest.groovy
Story is here:
https://repose.atlassian.net/browse/REP-4653
Updated Rackspace Auth User filter to read the request body of a Forgot Password request to grab the username, and it will only attempt to do so if the URL matches the current one used by Identity (trailing slash optional).  Otherwise, it will act like normal and try to read the request body like it was an auth request.  All of this only applies if it's a POST request, of course.
Also updated HERP filter to check the response from the origin service for an X-User-Name header if there wasn't one on the request.
=> REP-4653 UAE Lost Password

repose-aggregator/components/filters/rate-limiting-filter/src/test/java/org/openrepose/filters/ratelimiting/RateLimitingHandlerTest.java
Kicking the can.
We should kick the build off again on January 5, 2017 to ensure it's successful.
=> Timebomb - 2017 January Edition

repose-aggregator/components/filters/saml-policy-translation-filter/build.gradle, repose-aggregator/components/filters/saml-policy-translation-filter/src/main/scala/org/openrepose/filters/samlpolicy/SamlPolicyTranslationFilter.scala, repose-aggregator/components/filters/saml-policy-translation-filter/src/test/scala/org/openrepose/filters/samlpolicy/SamlPolicyTranslationFilterTest.scala, versions.properties
I'm just all around not happy with this. The method itself is basically a one-line call through to the SAML library with some exception translation wrapped around it. The SAML library is already expected to be tested, so I didn't want to write tests proving that method call works, but I also cannot easily mock it since it's a Scala `object`. PowerMock does not play nice with Scala, and there does not seem to be a Scalatest native mocking framework with the power I would need. So in the end, I need a valid `Document` and `XsltExecutable`. Those are a bit of a pain to create, and in the end, I didn't care about the content, so I wrote dumb placeholders. I actually started by stealing a test case from the `AttributeMapper` library, but going from the Identity mapping `String` to a …
=> REP-4804 Use SAML Library to do Translation

repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/samlpolicy/cachettl/saml-policy.cfg.xml, repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/samlpolicy/feedinvalidation/atom-feed-service.cfg.xml, repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/samlpolicy/feedinvalidation/saml-policy.cfg.xml, repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/samlpolicy/nocache/saml-policy.cfg.xml, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/keystonev2/AtomFeedResponseSimulator.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlCacheDisabledTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlCacheFeedInvalidationTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlCacheTtlTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/util/SamlPayloads.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/util/SamlUtilities.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/util/SamlUtilitiesSelfTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/services/atomfeed/AtomFeedServiceConnectionPoolTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/services/atomfeed/AtomFeedServiceReverseReadTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/services/atomfeed/AtomFeedServiceTest.groovy
Functional tests for the cache functionality in the SAML filter (not including live updating the cache configuration while Repose is running).
There will be more functional tests for the SAML functionality in a future PR.
=> REP-4816 SAML Cache Tests

repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlAttributeMappingTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlBasicValidationTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlCacheDisabledTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlCacheFeedInvalidationTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlCacheTtlTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlFlow10Test.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlFlow20Test.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/util/SamlPayloads.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/util/SamlUtilities.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/framework/mocks/MockIdentityV2Service.groovy
These are the start of the attribute mapping tests and subsequently the extended attributes testing, the translations going to the request and the response and how the cache may impact all of that.
=> REP-4816 SAML Attribute Mapping Tests

repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/samlpolicy/connectionheaders/http-connection-pool.cfg.xml, repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/samlpolicy/connectionheaders/saml-policy.cfg.xml, repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/samlpolicy/notracing/system-model.cfg.xml, repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/samlpolicy/tracingplain/system-model.cfg.xml, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlConnectionHeadersTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlNoTracingHeaderTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlTracingPlainHeaderTest.groovy
Added functional tests to verify the SAML filter allows you to:
1. configure headers to add to the requests being made to Identity for the token call
2. configure headers to add to the requests being made to Identity for the issuer/mapping policy calls
3. configure the tracing header for the calls going to Identity (token/issuer/mapping policy) including turning it on, turning it off, and enabling the plain text tracing header.
=> REP-4816 SAML Connection Headers Test

repose-aggregator/commons/commons-utilities/src/main/scala/org/openrepose/commons/utils/servlet/http/HttpServletRequestWrapper.scala, repose-aggregator/commons/commons-utilities/src/test/scala/org/openrepose/commons/utils/servlet/http/HttpServletRequestWrapperTest.scala, repose-aggregator/core/repose-core/src/main/java/org/openrepose/powerfilter/PowerFilter.java, repose-aggregator/core/repose-core/src/main/java/org/openrepose/powerfilter/PowerFilterChain.java
The issue was that the PowerFilterChain was setting a request attribute with the value of the parameter map. Since `getParameterMap` now reads the body for certain requests, we need to make sure that the body gets reset when it does. The request attribute in question is used in the HERP filter.
As I wrote that description, I was left wondering why we do that in the first place rather than using the parameter map in the request that we have when processing in the HERP filter. Does anyone remember?
I also left in some TODOs that I intend to work on for other things I noticed while digging around.
=> REP-5019 getParameter Not Returning SAMLResponse

repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlAttributeMappingTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlBasicValidationTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlCacheDisabledTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlCacheFeedInvalidationTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlCacheTtlTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlConnectionHeadersTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlFlow10Test.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlFlow20Test.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlKeystoneCredentialsTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlNoTracingHeaderTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlTracingPlainHeaderTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/util/SamlPayloads.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/util/SamlUtilities.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/framework/mocks/MockIdentityV2Service.groovy
I added a few test cases to the Flow 1.0 and Flow 2.0 validation tests around:
- Identity returning non-200 results (in both JSON and XML)
- a 200 response in a valid format that's neither JSON nor XML
- a 200 response that can't be parsed as the claimed format (in both JSON and XML)
The results are mostly the same except for the "can't be parsed" case where it'll still be a 200 in the Flow 1.0 case (since we really don't care) and a 502 in the Flow 2.0 case (since something went wrong when parsing something).
I also moved away from using my own content type strings and started using the `javax.ws.rs.core.MediaType` strings, and I started using a shared method to do execute the saml call where I could (i.e. tests without too many special cases).
=> REP-4816 SAML origin service response test

repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/samlpolicy/contentlength/http-connection-pool.cfg.xml, repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/samlpolicy/contentlength/scripting.cfg.xml, repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/samlpolicy/contentlength/system-model.cfg.xml, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlContentLengthTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/util/SamlPayloads.groovy
Added tests to verify that the SAML filter is either:
- Setting the content-length to the new size of the request body
- Using chunked encoding
And in both cases the other (unused) header should not be present.  A test was written for both Flow 1.0 and Flow 2.0.
=> REP-4816 SAML Content Length Test

repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/samlpolicy/feedconfigliveupdate/atom-feed-service.cfg.xml, repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/samlpolicy/feedconfigliveupdate/feedone/saml-policy.cfg.xml, repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/samlpolicy/feedconfigliveupdate/feedtwo/saml-policy.cfg.xml, repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/samlpolicy/feedconfigliveupdate/nofeed/saml-policy.cfg.xml, repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/samlpolicy/feedconfigliveupdate/nofeedlongttl/saml-policy.cfg.xml, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlFeedConfigLiveUpdateTest.groovy
Tests to confirm the filter supports updating the atom feed configuration while Repose is running
=> REP-4816 SAML Atom config live update test

repose-aggregator/artifacts/docker/build.gradle
Ignore the incorrect branch name. This just re-enables Docker image publishing. We should be good to go on that front with the most recent Puppet changes.
=> Re-enable Docker Image Publishing

repose-aggregator/tests/release-verification/src/scripts/fake_keystone_install_docker.sh, repose-aggregator/tests/release-verification/src/scripts/fake_origin_install_docker.sh
This is in response to the automatic release verification failure for the 8.4.1.0 release.
Looking at the verification process again reminded me of how much there is to fix there. The big problem is that the Dockerfile calls a number of scripts, and some of the scripts will succeed even if a command in the script fails. That is what we saw when `npm install` failed -- the logs made it look like the verification script failed, but that's only because Repose was returning 5xx responses since the mock Keystone service was never started (because its dependencies were never satisfied due to `npm install` failing).
=> Fixing immediate npm issue

.editorconfig
Turns out, while there is future potential, not too many settings are supported by EditorConfig at either the universal or domain-specific level.
These settings all seem reasonable to me. I will point out that I did not specify any additional settings for `*.adoc` files.
Reference: https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties
=> Adding initial .editorconfig file

README.md
In GitHub Markdown, headers with hashes on both sides require spaces to format correctly.
=> fix header markdown

repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlAttributeMappingTest.groovy
I removed the `@Ignore` on a test that was previously failing in SamlAttributeMappingTest due to how AttributeMapping was working.  AttributeMapping was updated and now the test passes.
=> Unignoring test in SamlAttributeMappingTest

repose-aggregator/tests/release-verification/src/docker/rpm/Dockerfile
From a comment I left elsewhere:
> The --unsafe-perm flag is used to support building the libxmljs library.
> Since there is no guarantee that libxmljs has been pre-compiled for the Docker image OS,
> node-gyp falls back to building the library. Since the Docker user is root, gyp
> creates a temporary directory for the build which breaks the Makefile. The flag
> makes things work again.
I'm not a huge fan of node, and I hope we move away from it in the future, but this fix should keep us working for now.
=> Temporary RPM Verification Fix

build.gradle, repose-aggregator/tests/release-verification/build.gradle
This seems to work for me locally on OS X.
If https://jenkins-proto.openrepose.org/job/release-verification-test/2/ passes, this change is good to go!
EDIT: If that job passes the Debian verification, it's good to go. The RPM verification process on master has an outstanding issue addressed by: https://github.com/rackerlabs/repose/pull/1723.
=> REP-5397 Upgrading the Docker Gradle plugin

build.gradle, repose-aggregator/build.gradle
This adds a central task when publishing that requires all artifacts build and test before anything gets released. This adds a check that will prevent some partial releases.
=> REP-5115 Adds a task between building and testing of artifacts and their publishing

repose-aggregator/src/docs/asciidoc/filters/scripting.adoc
Removed it from AsciiDoc for future generations.
=> Removed Ruby and Lua support from Scripting filter versioned docs

repose-aggregator/tests/performance-tests/Jenkinsfile
Sets the quiet period to a random length between 15 seconds and 10 minutes. Note that we may still hit rate limiting, but it should be pretty unlikely at this point.
=> REP-5645 Performance tests now with random quiet periods

repose-aggregator/components/services/atom-feed-service/atom-feed-service-impl/build.gradle, repose-aggregator/components/services/atom-feed-service/atom-feed-service-impl/src/test/scala/org/openrepose/nodeservice/atomfeed/impl/AtomFeedServiceImplTest.scala
The story is here:
https://repose.atlassian.net/browse/REP-5754
I left my findings in comments on the investigation subtask for any interested parties.
To "fix" the issue, I simply stopped relying on logs to verify behavior for this particular test. Using the logs was never the best solution, but since Akka is an asynchronous system, and since it's a closed system within the Atom Feed service (i.e., not publically accessible), testing it any other way would be a challenge. Well, challenge accepted. Gogo reflection!
=> REP-3664 Fixing the flaky test in AtomFeedServiceImplTest

build.gradle, repose-aggregator/artifacts/docker/build.gradle, repose-aggregator/tests/release-verification/build.gradle, repose-aggregator/tests/release-verification/src/docker/deb/Dockerfile
Just a few small changes that came out of https://repose.atlassian.net/browse/REP-4839 . I left a comment on that story with all of my thoughts and rationale. That comment explains why we don't really need `forcerm`.
=> REP-4643 Docker Release Verificaton Updates

repose-aggregator/tests/release-verification/src/scripts/verify.sh
Apparently I missed these when some names changed during the Vagrant removal work.
=> Fixing release verification by calling the right scripts

repose-aggregator/artifacts/docker/src/docker/centos/Dockerfile, repose-aggregator/artifacts/docker/src/docker/ubuntu/Dockerfile, repose-aggregator/src/docs/asciidoc/release-notes.adoc
This is based on the other Docker work from #1793 . This PR can be merged first.
=> REP-5766 Updated Dockerfiles to run Repose as repose user

repose-aggregator/src/docs/asciidoc/release-notes.adoc, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/attributemappingvalidation/AttributeMappingPolicyValidationFilterTest.groovy, versions.properties
Sending an awful looking invalid string bombs the yaml parser:
```
PUT /idm/cloud/v2.0/RAX-AUTH/federation/identity-providers/0601ba56aeda441ca105059c04286485/mapping HTTP/1.1
Host: localhost:8080
x-auth-token: AAD1PcpjilLpMJhPODlDMS9srFcMy6WRhoB3GXFBkUQoN_H4ZIAakcZKkFvkIij23AIDNfl3WfAq0k60LAI0QlIQlaz3swBlQ0wuhZ96SHItoYQqVs086wqUShb8vZO7Hea5nxwCMvem_w
content-type: text/yaml
Cache-Control: no-cache
Postman-Token: 312c3402-cb69-4b34-56aa-3b871dc35995
- just: write some
- yaml: 
- [here, and]
- {it: updates, in: real-time}
sdfsdds
```
Logs:
```
WARN  org.eclipse.jetty.servlet.ServletHandler - Error for /my/super/awesome/request/mapping
java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonParseException.<init>(Lcom/fasterxml/jackson/core/JsonParser;Ljava/lang/String;Ljava/lang/Throwabl …
```
=> (bug): Really bad yaml fails YAML parser and returns http 200 with empty body

build.gradle
This is the appropriate way to do this, even though the Sonar Scoverage plugin may not work for us and our end solution may necessitate further changes.
So this is more correct than what we currently have, but doesn't solve our problem?
=> REP-5765 Reporting Scoverage on a per-project basis

repose-aggregator/src/docs/asciidoc/_backends/haml/html5/document.html.haml
It just occurred to me that when I updated the HAML backend, I did not maintain my alteration which puts a version number in the footer.
This PR restores that functionality.
=> Adding the version information back into the footer

repose-aggregator/components/filters/saml-policy-translation-filter/src/test/scala/org/openrepose/filters/samlpolicy/SamlPolicyTranslationFilterTest.scala
This should fix the failing tests in #1826.
I put this together to show exactly why those tests are failing and how they could be fixed.
Jorge's description of the change:
>  # Old Behavior
> 
> There was no way to tell whether or not a SAML attribute should be
> rendered as an array or not. For example given the flowing SAML
> attributes:
> 
> ```xml
>  <saml2:Attribute Name="faws/canAddAWSAccount">
>    <saml2:AttributeValue xsi:type="xs:string">true</saml2:AttributeValue>
>  </saml2:Attribute>
>  <saml2:Attribute Name="faws/991049284483">
>    <saml2:AttributeValue xsi:type="xs:string">fanatical_aws:admin</saml2:AttributeValue>
>  </saml2:Attribute>
>  <saml2:Attribute Name="faws/042423532529">
>     <saml2:AttributeValue xsi:type="xs:string">fanatical_aws:observer</saml2:AttributeValue …
```
=> REP-6211 Multivalue Test Fix

repose-aggregator/components/services/atom-feed-service/atom-feed-service-impl/src/main/scala/org/openrepose/nodeservice/atomfeed/impl/auth/OpenStackIdentityV2AuthenticatedRequestFactory.scala
This was a warning in the Gradle build, so fixing it removes the warning.
=> Removing unreachable statement

repose-aggregator/src/docs/asciidoc/release-notes.adoc
Removed extraneous line that's messing up the formatting of the release notes.
=> Fixing 8.8.1.0 release notes formatting

versions/8.8.1.0/release-notes.html
Release notes for 8.8.1.0 are currently really messed up.
http://www.openrepose.org/versions/8.8.1.0/release-notes.html
I fixed the asciidoc locally (which will be in another PR), generated the HTML, and copied the file over this one (minus the version number and "last updated" date in the footer).
=> Fixing 8.8.1.0 release notes HTML

build.gradle
This will let the incremental build work correctly again, sonar looks like it's good to go. I can't find the integration test coverage anymore, so maybe we got rid of that when we added scoverage?
=> REP-6778 Fixed jacoco recording to not 'dirty' the test outputs

repose-aggregator/tests/performance-tests/Jenkinsfile, repose-aggregator/tests/performance-tests/roles/repose/tasks/install_repose.yml
Note: this work is actually accompanied by some work in Jenkins. The Jenkins work actually builds and copies the artifacts. See the following jobs:
https://jenkins.openrepose.org/job/repose-gradle-package/
https://jenkins.openrepose.org/job/performance-test/
=> REP-5461 Build DEB artifacts used by the performance tests once

repose-aggregator/artifacts/valve/src/test/scala/org/openrepose/valve/ReposeJettySSLTest.scala
So OpenJDK 8 changes its default security policy by disabling SSL ciphers. This PR fixes our SSL test by filtering enabled ciphers rather than disabled ciphers.
I initially thought that Jetty and Apache HttpClient would enable ciphers if they were supported, even if they were disabled by default, but that did not seem to work. So instead, I opted to just use enabled ciphers.
Note that the Java security policy can be edited system-wide by modifying the `java.security` file located somewhere under the JRE installation directory (at least, for both Hotspot and OpenJDK). In this case, we would have been interested in the `jdk.tls.disabledAlgorithms` setting.
=> REP-6967 Fixing the ReposeJettySSLTest

repose-aggregator/tests/performance-tests/roles/jmxtrans/templates/influxdb.json.j2
Data from a test run can be viewed as various graphs under the `JMX` panel on the [Grafana performance test dashboard](http://grafana.openrepose.org/d/000000005/performance-tests?orgId=1&from=1529677818996&to=1529679467580&var-testName=ScriptingFilterJavascriptSimulation&var-endpoint=Repose&var-requests=allRequests).
=> REP-6932 Collecting GC and Thread Data from Performance Tests

repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlFeedConfigLiveUpdateTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/services/datastore/RemoteDatastoreServiceTest.groovy
**ONLY MERGE THIS IF THE RELEASE FAILS DUE TO THESE TESTS FAILING**
These are known flaky tests, so to push the release forward, we are ignoring them.
As soon as the release succeeds, either this PR can be closed, or if merged, reverted.
=> Ignoring the RemoteDatastoreServiceTest suite

repose-aggregator/core/repose-core/src/test/scala/org/openrepose/commons/utils/classloader/EarClassProviderTest.scala
The new locking mechanism seems to reset the `lastModified` time, which in turn is being reported by the os with only second resolution. This is why when the test failed it was always off by exactly 1000 milliseconds.
=> Updated EarClassProviderTest to pass regularly.

repose-aggregator/docs/src/asciibinder/filters/keystone-v2.adoc, repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/core/headers/system-model.cfg.xml, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/core/headers/HeaderPassthroughTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/keystonev2/tenantandroleshandling/Keystonev2TenantAndRolesHandlingTest.groovy
Based off of #1998 since this test was affected by those changes.
There is only a single test failure. That failure is caused by Repose dropping request headers with an empty value. This behavior should not be accepted, but it is a known issue.
=> REP-7427 Adding tests to verify that Repose can handle header values with characters allowed by HTTP specification

repose-aggregator/docs/src/asciibinder/architecture/filter-chain.adoc, repose-aggregator/docs/src/asciibinder/filters/url-extractor-to-header.adoc, repose-aggregator/docs/src/asciibinder/recipes/getting-started.adoc, repose-aggregator/docs/src/asciibinder/welcome/release-notes.adoc, repose-aggregator/docs/src/asciibinder/welcome/ver-9-upgrade-notes.adoc
Fixed typos in the docs that made external links be interpreted as local anchors.
=> REP-7272 Fixing typos

build.gradle
This fixes Gradle configuration issues that arise when running with the `release` property.
The change itself no longer assumes that projects have a single signature for publication, and instead will publish every signature available. This accounts for the possibility of `configurations` being added to projects and `artifacts` being associated with them. A choice was made here to allow all artifacts to be signed and to publish all signatures. Note, however, that this configuration is merely the default publishing configuration, and that some projects (e.g., `valve`) override it.
=> Gradle Build Release Property Fix

repose-aggregator/tests/performance-tests/Jenkinsfile
For what information is available to use here, see: 
https://jenkins.io/doc/book/pipeline/getting-started/#global-variable-reference
=> REP-7355 Adding a Slack notification message on performance test failure

repose-aggregator/core/repose-core/src/main/scala/org/openrepose/commons/utils/classloader/EarClassProvider.scala, repose-aggregator/docs/src/asciibinder/welcome/release-notes.adoc
This replaces the `FileOutputStream` we were using with a `RandomAccessFile` and replaces the Apache Commons checksum function with our own. Doing so fixes two outstanding issues.
The first issue was that the `FileOutputStream` was not set to append mode, which caused the `FileOutputStream` to truncate its underlying file on instantiation. As a result, there may have been times where the file on disk was assumed to be valid when actually it was in a partially written state.
The second issue was that the `checksumCRC32` function would read the file using a `FileInputStream` that the function instantiated itself. After calculating the checksum, that function would close the `FileInputStream` which would release the lock we acquired from the channel underlying our `FileOutputStream`. Since …
=> REP-7663 Fixing EAR Unpacking (CRC)

repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/core/configloadingandreloading/TransitionBadToGoodConfigsTest.groovy, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/core/configloadingandreloading/TransitionGoodToBadConfigsTest.groovy
This removes or replaces some hardcoded sleeps in the `TransitionBadToGoodConfigsTest` and `TransitionGoodToBadConfigsTest`. 
I recorded the runtimes before/after these changes in the commit messages, so please look through those. Adding up the differences for the modified tests, this saved 2 minutes out of about 19 minutes on my laptop.
- Before: 18m48s
- After: 16m42s
=> Runtime improvements for config loading/reloading tests

repose-aggregator/tests/functional-test-framework/src/main/groovy/org/openrepose/framework/test/ReposeValveLauncher.groovy
This PR adds the ability to specify the repose heap size for individual tests.
- Decreased the default values in ReposeValveLauncher from 1536M and 1024M to 1024M and 512M
- To specify the heap size, replace 
`repose.start()` with 
`repose.start([reposeXmx:"<xmx>",reposeXms:"<xms>"])` 
where xmx is the max heap size, and xms is the min heap size. 
Ex: `repose.start([reposeXmx:"1536M",reposeXms:"1024M"])`
- Pull the values from the params to repose start if they are there, and insert them into the command to start repose.
Right now all the tests still use the default values.
=> REP-7720: Specify repose heap size for tests

repose-aggregator/components/services/open-tracing-service/build.gradle, repose-aggregator/core/repose-core/build.gradle, repose-aggregator/tests/functional-test-framework/build.gradle, versions.properties
The dependency check plugin is flagging an issue with our transitive dependency on `okhttp` (via `jaeger-core`).
Unfortunately, upgrading `jaeger-core` does not resolve this issue for us at this time. So instead we upgrade the library directly, preferring that to suppressing the issue.
=> REP-7776 Upgrading okhttp to resolve CVE-2018-20200

repose-aggregator/core/repose-core-api/src/main/java/org/openrepose/core/systemmodel/config/DestinationList.java, repose-aggregator/core/repose-core-api/src/main/resources/META-INF/schema/system-model/system-model.xsd, repose-aggregator/core/repose-core/src/main/java/org/openrepose/nodeservice/httpcomponent/HttpComponentRequestProcessor.java, repose-aggregator/core/repose-core/src/main/scala/org/openrepose/powerfilter/ReposeRoutingServlet.scala, repose-aggregator/core/repose-core/src/test/java/org/openrepose/nodeservice/httpcomponent/HttpComponentRequestProcessorTest.java, repose-aggregator/docs/src/asciibinder/architecture/system-model.adoc, repose-aggregator/docs/src/asciibinder/recipes/index.adoc, repose-aggregator/docs/src/asciibinder/recipes/project-karate.adoc, repose-aggregator/docs/src/asciibinder/welcome/release-notes.adoc, repose-aggregator/src/config/dependency-check/OWASP-Suppression.xml, repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/core/headers/headerencoding/scripting.cfg.xml, repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/core/headers/headerencoding/system-model.cfg.xml, repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/core/headers/HeaderEncodingTest.groovy, versions.properties
Allows header values to be url encoded before going to the origin service
=> REP-7966 Url encoding of Headers
