rackerlabs/repose

repose-aggregator/core/core-lib/src/test/scala/org/openrepose/core/spring/CoreSpringProviderTest.scala
repose-aggregator/pom.xml

Just ups the spring version to 4.1.2.
I expect everything to pass, but it's on a separate branch so the single commit won't dork with our awesomely passing spring branch.

Update the spring version to the latest n greatest

---

repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/services/httpconnectionpool/smallpool/http-connection-pool.cfg.xml
repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/services/httpconnectionpool/HttpClientStateTest.groovy
repose-aggregator/services/httpclient/impl/src/main/java/org/openrepose/services/httpclient/impl/HttpConnectionPoolProvider.java

Here's a pull request targeted to the 6.2.2.x branch.
Referencing #1228

Rep 1673 on 6.2.2.x

---

repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/uriidentity/uri-identity.cfg.xml
repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/uriidentity/UriIdentityTest.groovy

REP-1754 was merged into master however, still need to add a test for this

add test for REP-1754

---

repose-aggregator/pom.xml

Implements the desired functionality from https://repose.atlassian.net/browse/REP-1686
It works for all maven deployed artifacts, it happens to work for the DEBs (but it's not deployed to our artifact repository), it does not work for the RPMs.

Artifact signatures

---

repose-aggregator/core/core-lib/src/main/java/org/openrepose/core/spring/CoreSpringProvider.java
repose-aggregator/core/valve/src/main/scala/org/openrepose/valve/Main.scala
repose-aggregator/core/valve/src/main/scala/org/openrepose/valve/Valve.scala

Resolves REP-2036
Just makes the startup a bit quieter around valve stuff, it doesn't resolve any of the startup noise with regards to artifact loading.

Startup output cleanup

---

repose-aggregator/core/core-lib/src/test/scala/org/openrepose/core/services/logging/LoggingServiceImplTest.scala

Unfortunately, I couldn't remove all the sleeps. There must be a short
period of silence for log4j to be willing to change it's loggers around.
This does prevent it from flaking out, so it will retry many times to
make sure all the assertions pass

Refactor the Log4j reconfiguration so it doesn't flake out any more

---

repose-aggregator/pom.xml

- add a profile to pom for veracode scan jobs
Notes, close previous Security Veracode Scan and open this new one branch out from current master to avoid all messy merge conflict.

Rep 1841 veracode scan jobs

---

repose-aggregator/components/filters/client-auth/src/main/java/org/openrepose/filters/clientauth/common/AuthGroupCache.java
repose-aggregator/components/filters/client-auth/src/main/java/org/openrepose/filters/clientauth/common/AuthUserCache.java
repose-aggregator/components/filters/client-auth/src/main/java/org/openrepose/filters/clientauth/common/AuthenticationHandler.java
repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/clientauthn/AtomFeedResponseSimulator.groovy
repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/clientauthn/cache/InvalidateCacheUsingAtomFeedTest.groovy

This actually makes the cache keys for stuff delete properly.
Fixes: https://repose.atlassian.net/browse/REP-2130

Cache verification stuff

---

repose-aggregator/commons/configuration/src/test/resources/unmarshallerValidator/xsd/container-configuration.xsd
repose-aggregator/core/core-service-api/src/main/resources/META-INF/schema/container/container-configuration.xsd

Fixed some typos in the documentation of the container-configuration schema definition.

REP-2177 Fixed Typos

---

repose-aggregator/installation/configs/docs/DEPENDENCIES-EXTENSIONS-FILTER-BUNDLE.txt
repose-aggregator/installation/configs/docs/DEPENDENCIES-FILTER-BUNDLE.txt
repose-aggregator/installation/configs/docs/DEPENDENCIES.txt
repose-aggregator/installation/deb/repose-cli-utils/pom.xml
repose-aggregator/installation/deb/repose-extensions-filter-bundle/pom.xml
repose-aggregator/installation/deb/repose-filter-bundle/pom.xml
repose-aggregator/installation/deb/repose-valve/pom.xml
repose-aggregator/installation/deb/repose-war/pom.xml
repose-aggregator/installation/rpm/repose-cli-utils/pom.xml
repose-aggregator/installation/rpm/repose-extensions-filter-bundle/pom.xml
repose-aggregator/installation/rpm/repose-filter-bundle/pom.xml
repose-aggregator/installation/rpm/repose-valve/pom.xml
repose-aggregator/installation/rpm/repose-war/pom.xml
scripts/DependencyCheckHelper.sh

FYI, Valve and War end up being the same since the DD uses jetty and that was the only difference.

new dependency files

---

repose-aggregator/core/core-lib/src/main/java/org/openrepose/nodeservice/httpcomponent/RequestProxyServiceImpl.java
repose-aggregator/core/core-lib/src/main/java/org/openrepose/powerfilter/PowerFilter.java
repose-aggregator/core/core-lib/src/main/resources/log4j2.component.properties
repose-aggregator/core/core-lib/src/test/groovy/org/openrepose/nodeservice/httpcomponent/RequestProxyServiceImplTest.groovy
repose-aggregator/core/core-service-api/src/main/java/org/openrepose/core/logging/TracingKey.java
repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/core/powerfilter/tracing/log4j2-test.xml
repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/core/tracing/client-auth-n.cfg.xml
repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/core/tracing/distdatastore/dist-datastore.cfg.xml
repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/core/tracing/distdatastore/system-model.cfg.xml
repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/core/tracing/log4j2-test.xml
repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/core/tracing/system-model.cfg.xml
repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/herp/tracinglog/log4j2-test.xml
repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/valkyrie/tracinglog/log4j2-test.xml
repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/core/powerfilter/TracingHeaderTest.groovy
repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/core/tracing/TracingDistDatastoreTest.groovy
repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/core/tracing/TracingLogTest.groovy
repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/herp/HerpTracingLogTest.groovy
repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/valkyrie/TracingLogWValkyrieTest.groovy
repose-aggregator/installation/configs/core/log4j2.xml
repose-aggregator/pom.xml
repose-aggregator/services/datastore/impl/pom.xml
repose-aggregator/services/datastore/impl/src/main/java/org/openrepose/nodeservice/distributed/servlet/DistributedDatastoreServlet.java
repose-aggregator/services/service-client/impl/pom.xml
repose-aggregator/services/service-client/impl/src/main/java/org/openrepose/core/services/serviceclient/akka/impl/ActorRequest.java
repose-aggregator/services/service-client/impl/src/main/java/org/openrepose/core/services/serviceclient/akka/impl/AkkaServiceClientImpl.java
repose-aggregator/services/service-client/impl/src/main/java/org/openrepose/core/services/serviceclient/akka/impl/AuthGetRequest.java
repose-aggregator/services/service-client/impl/src/main/java/org/openrepose/core/services/serviceclient/akka/impl/AuthPostRequest.java
repose-aggregator/services/service-client/impl/src/main/java/org/openrepose/core/services/serviceclient/akka/impl/AuthTokenFutureActor.java
repose-aggregator/services/service-client/impl/src/test/scala/org/openrepose/core/services/serviceclient/akka/impl/AkkaServiceClientImplTest.scala

Rep 1828 tracing

---

repose-aggregator/components/filters/client-auth/src/main/java/org/openrepose/filters/clientauth/openstack/OpenStackAuthenticationHeaderManager.java
repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/ratelimiting/withclientauthngroups/client-auth-n.cfg.xml
repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/ratelimiting/withclientauthngroups/rate-limiting.cfg.xml
repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/ratelimiting/withclientauthngroups/system-model.cfg.xml
repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/clientauthn/tenantvalidation/NonTenantedNonDelegableNoServiceAdminRolesTest.groovy
repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/clientauthn/tenantvalidation/TenantedNonDelegableTest.groovy
repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/ratelimiting/RateLimitingWClientAuthGroupTest.groovy
repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/framework/mocks/MockIdentityService.groovy

Here's the quick and dirty fix.
If all tests pass, this is probably good to go.
Refer to #1332 for more info.

Removing quality as part of the value

---

repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/core/tracing/distdatastore/dist-datastore.cfg.xml
repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/core/tracing/distdatastore/system-model.cfg.xml
repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/core/tracing/TracingDistDatastoreTest.groovy
repose-aggregator/services/datastore/impl/src/main/java/org/openrepose/core/services/datastore/impl/distributed/remote/command/AbstractRemoteCommand.java
repose-aggregator/services/datastore/impl/src/test/groovy/org/openrepose/core/services/datastore/impl/distributed/remote/command/AbstractRemoteCommandTest.groovy

Cannot run functional tests on my computer, so opening pull request.

Rep 2404 - DD Service not sending trace id

---

repose-aggregator/commons/utilities/src/main/java/org/openrepose/commons/utils/servlet/http/ResponseMode.java
repose-aggregator/commons/utilities/src/main/scala/org/openrepose/commons/utils/servlet/http/HttpServletResponseWrapper.scala

Everyone take a look, tell me if there's any case you can think of that i haven't accounted for.
This isn't all the methods we'll have to write, these are just the ones that came with the interface (so i could document the fail state), and the ones we'd be adding.

New Response Wrapper Skeleton

---

repose-aggregator/installation/configs/extensions/validator.cfg.xml

Update validator.cfg.xml installation configuration with proper attribute name

Update validator.cfg.xml installation configuration

---

repose-aggregator/components/filters/valkyrie-authorization/src/main/resources/META-INF/schema/config/valkyrie-authorization.xsd
repose-aggregator/components/filters/valkyrie-authorization/src/main/resources/META-INF/schema/examples/valkyrie-authorization.cfg.xml
repose-aggregator/components/filters/valkyrie-authorization/src/main/scala/org/openrepose/filters/valkyrieauthorization/ValkyrieAuthorizationFilter.scala
repose-aggregator/components/filters/valkyrie-authorization/src/test/scala/org/openrepose/filters/valkyrieauthorization/ValkyrieAuthorizationFilterTest.scala
repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/valkyrie/collectionresources/valkyrie-authorization.cfg.xml
repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/valkyrie/translatepermissionstoroles/validator.cfg.xml
repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/valkyrie/translatepermissionstoroles/valkyrie-authorization.cfg.xml
repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/valkyrie/CollectResourceBaseOnPermissionTest.groovy
repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/valkyrie/TranslatePermissionsToRolesTest.groovy
repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/framework/mocks/MockValkyrie.groovy

This also removes the authorization checks other than if a device id is present

This will translate account level permissions to roles

---

repose-aggregator/components/filters/herp/src/main/scala/org/openrepose/filters/herp/HerpFilter.scala
repose-aggregator/components/filters/openstack-identity-v3/src/main/scala/org/openrepose/filters/openstackidentityv3/OpenStackIdentityV3Handler.scala

Replaced .size with .length on string since is causes an additional implicit conversion.
Replaced filter and non-emptiness check with exists.
Replaced .map and .flatten with .flatMap.

Fixed a few minor things found by IntelliJ IDEA's static analysis tools.

---

repose-aggregator/installation/configs/etc/init.d/deb/repose-valve
repose-aggregator/installation/configs/etc/init.d/rpm/repose-valve
repose-aggregator/installation/configs/etc/sysconfig/repose

Manually tested, and this seems to work just fine.

REP-2941 Use the Java environment variable rather than checking the path

---

repose-aggregator/components/filters/translation/src/main/java/org/openrepose/filters/translation/httpx/HttpxMarshaller.java
repose-aggregator/components/filters/translation/src/main/java/org/openrepose/filters/translation/httpx/HttpxMarshallerUtility.java
repose-aggregator/components/filters/translation/src/main/java/org/openrepose/filters/translation/xslt/xmlfilterchain/XmlFilterChainBuilder.java
repose-aggregator/functional-tests/test-support/src/main/java/org/openrepose/commons/utils/test/mocks/MockServiceResource.java
repose-aggregator/functional-tests/test-support/src/main/java/org/openrepose/commons/utils/test/mocks/auth/osids/KeystoneResource.java
repose-aggregator/functional-tests/test-support/src/main/java/org/openrepose/commons/utils/test/mocks/auth/osids/providers/KeystonePropertiesProvider.java

Simple updates to resolve some sonar violations.

Sonar violations 2016-01-06

---

repose-aggregator/commons/utilities/src/test/java/org/openrepose/commons/utils/http/header/HeaderValueImplTest.java
repose-aggregator/components/filters/herp/src/test/scala/org/openrepose/filters/herp/HerpFilterTest.scala
repose-aggregator/external/service-clients/auth/src/test/java/org/openrepose/common/auth/openstack/OpenStackTokenTest.java
repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/core/powerfilter/ApiValidatorRunSmokeTest.groovy

Most of these were tied to the order of the underlying Collection which is not guaranteed.
I also fixed a couple of typos and some findings from the static analysis tools that dealt with Generics.

Fix updated unit tests for Java 8.

---

repose-aggregator/components/filters/forwarded-proto/src/main/scala/org/openrepose/filters/forwardedproto/ForwardedProtoFilter.scala

Updated usage of old wrapper to new wrapper.

REP-3260 Forwarded Proto filter updated to use new wrappers

---

repose-aggregator/components/filters/valkyrie-authorization/pom.xml
repose-aggregator/components/filters/valkyrie-authorization/src/main/scala/org/openrepose/filters/valkyrieauthorization/ValkyrieAuthorizationFilter.scala
repose-aggregator/components/filters/valkyrie-authorization/src/test/scala/org/openrepose/filters/valkyrieauthorization/ValkyrieAuthorizationFilterTest.scala

Tracking repose-8-staging.
For old comments, see:
#1458

REP-3278 Valkyrie filter wrapper replacement

---

repose-aggregator/commons/commons-utilities/build.gradle
repose-aggregator/commons/commons-utilities/pom.xml
repose-aggregator/commons/commons-utilities/src/main/scala/org/openrepose/commons/utils/servlet/http/HttpServletRequestWrapper.scala
repose-aggregator/commons/commons-utilities/src/test/scala/org/openrepose/commons/utils/servlet/http/HttpServletRequestWrapperTest.scala
repose-aggregator/components/filters/valkyrie-authorization-filter/src/test/scala/org/openrepose/filters/valkyrieauthorization/ValkyrieAuthorizationFilterTest.scala

- URI/URL manipulation support
- Query parameter manipulation support

Wrapper changes

---

repose-aggregator/components/repose-lint/src/main/scala/org/openrepose/lint/CommandExecutor.scala
repose-aggregator/components/repose-lint/src/main/scala/org/openrepose/lint/LintConfig.scala
repose-aggregator/components/repose-lint/src/main/scala/org/openrepose/lint/commands/VerifyTryItNowCommand.scala
repose-aggregator/components/repose-lint/src/test/resources/configs/customrole/keystone-v2.cfg.xml
repose-aggregator/components/repose-lint/src/test/resources/configs/customrole/system-model.cfg.xml
repose-aggregator/components/repose-lint/src/test/scala/org/openrepose/lint/commands/VerifyTryItNowCommandTest.scala
repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/reposelint/keystonev2/authzwconfigrole/keystone-v2.cfg.xml
repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/reposelint/keystonev2/authzwconfigrole/system-model.cfg.xml
repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/reposelint/keystonev2/tenanted/wconfigrole/keystone-v2.cfg.xml
repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/reposelint/keystonev2/tenanted/wconfigrole/system-model.cfg.xml
repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/reposelint/ReposeLintWReposeVerTest.groovy
repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/reposelint/ReposeLintWRoleConfigTest.groovy
repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/framework/ReposeLintLauncher.groovy
repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/framework/TestProperties.groovy

We will need to release from this branch after code and QE review are completed.

REP-3743 Adding configurable role to the verify-try-it-now command

---

repose-aggregator/core/repose-core-api/build.gradle
repose-aggregator/core/repose-core-api/src/main/scala/org/openrepose/core/filter/AbstractConfiguredFilter.scala
repose-aggregator/core/repose-core-api/src/test/resources/stubbed.xsd
repose-aggregator/core/repose-core-api/src/test/scala/org/openrepose/core/filter/AbstractConfiguredFilterTest.scala

The abstract configured filter in it's own pr so we can pull it in sooner

Abstract Configured Filter

---

README.md

I updated the README.  I removed some stuff I thought was better explained in the docs and added a bunch of links.

REP-3960 - Update README

---

repose-aggregator/components/filters/body-patcher-filter/src/main/scala/org/openrepose/filters/bodypatcher/BodyPatcherFilter.scala
repose-aggregator/components/filters/body-patcher-filter/src/test/scala/org/openrepose/filters/bodypatcher/BodyPatcherFilterTest.scala

This resolves the failing tests.

Removed feature to allow blank bodies to work on the patcher

---

repose-aggregator/components/filters/compression-filter/src/test/scala/org/openrepose/filters/compression/CompressionFilterCompleteTest.scala
repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/compression/binary/add-header.cfg.xml
repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/compression/binary/system-model.cfg.xml
repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/compression/CompressionBinaryTest.groovy
repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/compression/CompressionHeaderTest.groovy

Added some tests and updated one place to make testing easier.
The end result is that we can confirm the new wrappers fixed the wonkiness happening with the compression filter in v6.x.

REP-4028 Confirm Compression filter works as expected.

---

repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/keystonev2/AtomFeedResponseSimulator.groovy
repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/services/atomfeed/AtomFeedServiceReverseReadTest.groovy
repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/services/atomfeed/AtomFeedServiceTest.groovy

I added a race condition in the functional tests for REP-3415.  This pull request is to fix that.
Code review task:
https://repose.atlassian.net/browse/REP-4162

REP-3415: Atom feed functional tests updated to remove race conditions

---

repose-aggregator/components/filters/rate-limiting-filter/src/test/java/org/openrepose/filters/ratelimiting/RateLimitingHandlerTest.java
repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/core/classloader/ClassLoaderTest.groovy

Moving time bombs to October 5, 2016

---

repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/apivalidator/metadataextension/maskraxroles403/validator.cfg.xml
repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/apivalidator/metadataextension/metadataext.wadl.xml
repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/apivalidator/metadataextension/raxroleenabledfalse/validator.cfg.xml
repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/apivalidator/metadataextension/system-model.cfg.xml
repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/apivalidator/metadataextension/validator.cfg.xml
repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/apivalidator/metadataextension/MetadataExtensionTest.groovy
repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/apivalidator/metadataextension/MetadataExtensionWithMaskRaxRoles403Test.groovy
repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/apivalidator/metadataextension/RaxRolesEnabledFalseTest.groovy

These are tests that were written some time ago and the original branch, #1576 REP-2604-metadata-extension,  is no longer mergeable.

REP-2604 API-Checker Metadata Extensions tests

---

repose-aggregator/components/filters/herp/src/main/scala/org/openrepose/filters/herp/HerpFilter.scala
repose-aggregator/components/filters/herp/src/test/scala/org/openrepose/filters/herp/HerpFilterTest.scala
repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/herp/HerpCloudfeedCADFdefaultTemplateTest.groovy

This branch is not expected to be merged. This PR is to make code review easy before a release is cut off of this branch.

REP-4491 Handling options cadf method and unknown cadf methods

---

repose-aggregator/components/filters/rate-limiting-filter/src/test/java/org/openrepose/filters/ratelimiting/RateLimitingHandlerTest.java
repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/core/classloader/ClassLoaderTest.groovy

REP-4515 Moved time bombs from October 5, 2016 to January 5, 2017

---

repose-aggregator/components/filters/rate-limiting/src/test/java/org/openrepose/filters/ratelimiting/RateLimitingHandlerTest.java
repose-aggregator/components/filters/versioning/src/test/java/org/openrepose/filters/versioning/VersioningHandlerTest.java
repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/core/classloader/ClassLoaderTest.groovy
repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/experimental/servletContract/ServletContractFilterTest.groovy

I expect that this will be reverted after the release has been completed. Then the release branch can be merged into master.

Bumping all time bombs in preparation for the 7 release

---

repose-aggregator/components/filters/valkyrie-authorization/src/main/resources/META-INF/schema/config/valkyrie-authorization.xsd
repose-aggregator/components/filters/valkyrie-authorization/src/main/resources/META-INF/schema/examples/valkyrie-authorization.cfg.xml
repose-aggregator/components/filters/valkyrie-authorization/src/main/scala/org/openrepose/filters/valkyrieauthorization/ValkyrieAuthorizationFilter.scala
repose-aggregator/components/filters/valkyrie-authorization/src/test/scala/org/openrepose/filters/valkyrieauthorization/ValkyrieAuthorizationFilterTest.scala
repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/valkyrie/passnondedicatedtenant/system-model.cfg.xml
repose-aggregator/functional-tests/spock-functional-test/src/test/configs/features/filters/valkyrie/passnondedicatedtenant/valkyrie-authorization.cfg.xml
repose-aggregator/functional-tests/spock-functional-test/src/test/groovy/features/filters/valkyrie/PassNonDedicatedTenantTest.groovy

This branch is not expected to be merged. This PR is to make code review easy before a release is cut off of this branch.

REP-4497 Add Valkyrie Filter Bypass for Non-dedicated Tenants

---

repose-aggregator/components/filters/api-validator-filter/src/main/java/org/openrepose/filters/apivalidator/ValidatorConfigurator.java
repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/apivalidator/authenticatedBy/authenticatedBy.wadl
repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/apivalidator/authenticatedBy/validator.cfg.xml
repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/apivalidator/AuthenticatedByTest.groovy

When the API Checker configuration is being created in Repose, we're now turning on the authenticated-by extension.  Functional tests were also added.

REP4446 - Turned on authenticated-by extension in our API Checker instance

---

build.gradle
repose-aggregator/build.gradle
repose-aggregator/src/docs/asciidoc/index.adoc
src/docs/asciidoc/index.adoc

Adjusted build.gradle and asciidoc go publish a versions folder to ghpages on a release build. This will also require adding a blank "versions.html" file to the gh-pages branch.

Rep 4082 vdocs

---

repose-aggregator/tests/release-verification/src/fake-services/fake-keystone2/app.js
repose-aggregator/tests/release-verification/src/fake-services/fake-keystone2/package.json
repose-aggregator/tests/release-verification/src/fake-services/fake-origin/app.js
repose-aggregator/tests/release-verification/src/fake-services/fake-origin/package.json
repose-aggregator/tests/release-verification/src/fake-services/fake-valkyrie2/package.json
repose-aggregator/tests/release-verification/src/scripts/node_install.sh
repose-aggregator/tests/release-verification/src/vagrant/deb/Vagrantfile
repose-aggregator/tests/release-verification/src/vagrant/rpm/Vagrantfile

This still requires some rework in the Vagrant files.

Updated the Release Verification Fake Services to Node v6 LTS.

---

repose-aggregator/commons/commons-utilities/src/main/scala/org/openrepose/commons/utils/servlet/http/HttpServletResponseWrapper.scala
repose-aggregator/commons/commons-utilities/src/test/scala/org/openrepose/commons/utils/servlet/http/HttpServletResponseWrapperTest.scala
repose-aggregator/src/docs/asciidoc/release-notes.adoc
repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/core/wrappers/response/response-messaging.cfg.xml
repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/core/wrappers/response/scripting1.cfg.xml
repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/core/wrappers/response/scripting2.cfg.xml
repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/core/wrappers/response/system-model.cfg.xml
repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/core/wrappers/response/ResponseWrapperTest.groovy

PR is because I rebased this branch onto Bill's branch.
Original PR is here:
https://github.com/rackerlabs/repose/pull/1633

REP-4764 Fixing sendError method in HttpServletResponseWrapper

---

repose-aggregator/components/filters/herp-filter/src/main/scala/org/openrepose/filters/herp/HerpFilter.scala
repose-aggregator/components/filters/herp-filter/src/test/scala/org/openrepose/filters/herp/HerpFilterTest.scala
repose-aggregator/src/docs/asciidoc/filters/herp.adoc
repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/herp/HerpCloudfeedCADFdefaultTemplateTest.groovy
repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/herp/HerpUserAccessEventFilterTest.groovy

This insures a truly unique value while still retaining the tracing header's value as part of the UAE's key.

REP-4841 Added an additional GUID for following the Tracing header's value

---

repose-aggregator/components/filters/saml-policy-translation-filter/src/main/scala/org/openrepose/filters/samlpolicy/SamlPolicyTranslationFilter.scala
repose-aggregator/components/filters/saml-policy-translation-filter/src/test/scala/org/openrepose/filters/samlpolicy/SamlPolicyTranslationFilterTest.scala

REP-4908 Response Validation

---

repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlKeystoneCredentialsTest.groovy

Added tests for keystone credentials in the configs.

REP-4816 SAML Keystone Creds Config Tests

---

repose-aggregator/tests/functional-tests/build.gradle
repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/samlpolicy/flow1_0/saml-policy.cfg.xml
repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlFlow10Test.groovy
repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlFlow20Test.groovy
repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/util/SamlPayloads.groovy
repose-aggregator/tests/functional-tests/src/integrationTest/groovy/framework/mocks/MockIdentityV2Service.groovy

Finishing up the flow validation tests for SAML.
There is one remaining TODO.  I e-mailed Jorge asking what the test should be expecting.

REP-4816 SAML Flow Validation tests

---

repose-aggregator/components/filters/saml-policy-translation-filter/src/main/scala/org/openrepose/filters/samlpolicy/SamlPolicyTranslationFilter.scala

This addresses the comments left on #1660.
And cleans up a few things that were found along the way.

REP-4857 SAML filter modify response Part1/Take2

---

repose-aggregator/build.gradle
repose-aggregator/src/docs/asciidoc/_backends/haml/html5/document.html.haml

So this was more of a pain than I was initially expecting. The commits tell a story. Or half a story, anyway.
I initially attempted to stick the version in a `docinfo-footer.html` filter. Unfortunately, I found that the `docinfo-footer` content was being placed below the `footer` div with the formatting. So that didn't work. My test `docinfo-footer.html` file had these contents:
`Version: {project-version}`
So next up was messing with the CSS. I noticed that the theme we're using builds a stylesheet that provides `::before` and `::after` hooks into the footer. Well, it was easy enough to get text in the right place by modifying the CSS to exploit that, but asciidoctor attributes were not available. That is, getting the version in the CSS would have required more work than I wanted to do. …

REP-5051 Add version to footer of docs

---

repose-aggregator/commons/commons-utilities/src/main/scala/org/openrepose/commons/utils/servlet/http/HttpServletRequestWrapper.scala

I'm just documenting the behavior.

REP-5029 Get Parameters From super.getParameterMap in Wrapper

---

repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/services/datastore/remote/client/rate-limiting.cfg.xml
repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/services/datastore/remote/datastore/scripting.cfg.xml
repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/services/datastore/remote/datastore/system-model.cfg.xml
repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/services/datastore/RemoteDatastoreServiceTest.groovy

Added functional tests for the Remote Datastore story:
https://repose.atlassian.net/browse/REP-5265
(PR being re-submitted to test Jenkins.)

REP-5265 Remote Datastore QE - Attempt #2

---

versions/8.3.0.1/filters/scripting.html
versions/8.4.0.1/filters/scripting.html
versions/8.4.0.2/filters/scripting.html
versions/8.4.1.0/filters/scripting.html
versions/8.5.0.1/filters/scripting.html

Removed Ruby and Lua support from Scripting filter docs (old versions)

---

repose-aggregator/src/docs/asciidoc/release-notes.adoc

There were a few inconsistencies in the release notes. There was also a bad link for one of the JIRAs.

Release notes - updates for consistency

---

build.gradle
repose-aggregator/src/docs/asciidoc/release-notes.adoc

Bumping the version to 8.6.0.0

---

repose-aggregator/artifacts/docker/build.gradle

Somebody called the wrong method

Docker Fix

---

repose-aggregator/src/docs/asciidoc/architecture/performance.adoc
repose-aggregator/tests/performance-tests/Jenkinsfile
repose-aggregator/tests/performance-tests/roles/cloud_resource_create/defaults/main.yml
repose-aggregator/tests/performance-tests/roles/gatling/files/simulations/filters/herp/HerpFilterSimulation.scala
repose-aggregator/tests/performance-tests/roles/gatling/files/simulations/filters/keystonev2/KeystoneV2FilterSimulation.scala
repose-aggregator/tests/performance-tests/roles/gatling/files/simulations/filters/saml/SamlFilterSimulation.scala
repose-aggregator/tests/performance-tests/roles/gatling/files/simulations/filters/valkyrie/ValkyrieFilterSimulation.scala
repose-aggregator/tests/performance-tests/roles/gatling/tasks/fetch_results.yml
repose-aggregator/tests/performance-tests/roles/repose/tasks/configure_repose.yml
repose-aggregator/tests/performance-tests/test_vars/filters/herp.yml
repose-aggregator/tests/performance-tests/test_vars/filters/keystonev2.yml
repose-aggregator/tests/performance-tests/test_vars/filters/saml.yml
repose-aggregator/tests/performance-tests/test_vars/filters/scripting.yml
repose-aggregator/tests/performance-tests/test_vars/filters/valkyrie.yml

Created Jenkinsfile to orchestrate running the performance tests.
Also made some updates to the Ansible playbooks to make the performance tests work while running on Jenkins (specifically using the Jenkins plugin).
And updated some of the performance test simulation names to make them consistent.

REP-5459 Performance Test orchestration in Jenkins

---

repose-aggregator/tests/performance-tests/Jenkinsfile

When this change comes in we'll need to update the performance job itself to running only the test startup script.

REP-5643 Always run the cleanup job

---

css/style.css
scss/_custom.scss

The icons relative position changed for some reason that I can't figure out (for I am certainly no CSS expert, much less a Compass expert), so I kind of cheated and adjusted their relational adjustment to make things work. I also fell back to the old slide spacing and just added exceptions for the information slides at the bottom of the page to make things look a little nicer.

REP-6050 Fixing the page styling

---

repose-aggregator/src/docs/asciidoc/filters/tenant-culling.adoc

Set the Release in the Tenant Culling filter doc to 8.7.0.0

Set the Release in the Tenant Culling filter doc

---

build.gradle
repose-aggregator/build.gradle

Also updated the build to fail on ASCII Doctor `WARNING`'s.

REP-5536 Added the new linkchecker plugin to the build.

---

repose-aggregator/components/services/phone-home-service/build.gradle
repose-aggregator/components/services/phone-home-service/src/main/scala/org/openrepose/core/services/phonehome/PhoneHomeService.scala
repose-aggregator/components/services/phone-home-service/src/test/scala/org/openrepose/core/services/phonehome/PhoneHomeServiceTest.scala

REP-6654 Instrumenting Phone Home service for OpenTracing

---

repose-aggregator/components/services/atom-feed-service/atom-feed-service-impl/build.gradle
repose-aggregator/components/services/atom-feed-service/atom-feed-service-impl/src/main/scala/org/openrepose/nodeservice/atomfeed/impl/AtomFeedServiceImpl.scala
repose-aggregator/components/services/atom-feed-service/atom-feed-service-impl/src/main/scala/org/openrepose/nodeservice/atomfeed/impl/actors/FeedReader.scala
repose-aggregator/components/services/atom-feed-service/atom-feed-service-impl/src/test/scala/org/openrepose/nodeservice/atomfeed/impl/AtomFeedServiceImplTest.scala
repose-aggregator/components/services/atom-feed-service/atom-feed-service-impl/src/test/scala/org/openrepose/nodeservice/atomfeed/impl/actors/FeedReaderTest.scala

REP-6654 Instrumenting the Atom Feed Service for OpenTracing

---

repose-aggregator/commons/commons-utilities/src/main/scala/org/openrepose/commons/utils/opentracing/ScopeHelper.scala
repose-aggregator/components/services/datastore-service/datastore-service-impl/build.gradle
repose-aggregator/components/services/datastore-service/datastore-service-impl/src/main/java/org/openrepose/nodeservice/distributed/jetty/DistributedDatastoreLauncherService.java
repose-aggregator/components/services/datastore-service/datastore-service-impl/src/main/java/org/openrepose/nodeservice/distributed/servlet/DistributedDatastoreServlet.java
repose-aggregator/components/services/datastore-service/datastore-service-impl/src/test/scala/org/openrepose/nodeservice/distributed/servlet/DistributedDatastoreServletTest.scala
repose-aggregator/core/repose-core-api/build.gradle
repose-aggregator/core/repose-core/src/main/java/org/openrepose/powerfilter/PowerFilter.java

This also includes a non-functional formatting of the `PowerFilter` that removed a few more unnecessary imports.

REP-6654 dist datastore

---

repose-aggregator/tests/performance-tests/roles/gatling/files/simulations/filters/regexrbac/RegexRbacFilterSimulation.scala
repose-aggregator/tests/performance-tests/roles/repose/files/config/filters/regexrbac/regex-rbac.cfg.xml

REP-6878 Regex RBAC Perf Test Fix

---

repose-aggregator/tests/performance-tests/roles/gatling/files/simulations/filters/saml/SamlFilterNoCacheSimulation.scala
repose-aggregator/tests/performance-tests/roles/repose/files/mocks/filters/saml/keystone.js
repose-aggregator/tests/performance-tests/roles/repose/files/mocks/filters/saml/large-policy.yaml
repose-aggregator/tests/performance-tests/roles/repose/tasks/run_mocks.yml

A few modifications to get the titular performance test running the way it is supposed to be running.

REP-6862 SAML Policy Translation Filter Perf Test Fix

---

repose-aggregator/src/docs/asciidoc/architecture/performance.adoc
repose-aggregator/tests/performance-tests/group_vars/all.yml
repose-aggregator/tests/performance-tests/library/repose.py
repose-aggregator/tests/performance-tests/roles/jmxtrans/defaults/main.yml
repose-aggregator/tests/performance-tests/roles/jmxtrans/handlers/main.yml
repose-aggregator/tests/performance-tests/roles/jmxtrans/tasks/configure.yml
repose-aggregator/tests/performance-tests/roles/jmxtrans/tasks/install-debian.yml
repose-aggregator/tests/performance-tests/roles/jmxtrans/tasks/install-redhat.yml
repose-aggregator/tests/performance-tests/roles/jmxtrans/tasks/install.yml
repose-aggregator/tests/performance-tests/roles/jmxtrans/tasks/main.yml
repose-aggregator/tests/performance-tests/roles/jmxtrans/tasks/start.yml
repose-aggregator/tests/performance-tests/roles/jmxtrans/templates/influxdb.json.j2
repose-aggregator/tests/performance-tests/roles/repose/defaults/main.yml
repose-aggregator/tests/performance-tests/roles/repose/templates/systemd/local.conf.j2
repose-aggregator/tests/performance-tests/start_test.yml
repose-aggregator/tests/performance-tests/test_vars/filters/saml.yml

This PR requires the companion infrastructure PR at:
https://github.com/rackerlabs/repose-infrastructure-ng/pull/119

REP-6882 (REP-5334) Collect JMX Metrics for Performance Tests

---

repose-aggregator/tests/performance-tests/library/repose.py

By leaving a comment with the name of the performance test to be run, I should be able to verify that the performance test in question will at least run to completion. The result of the run should be posted as a check on this PR. Note that a failure of the check only indicates that the performance test failed to run, not that a certain performance threshold was not met. Similarly, a success only indicates that the performance test ran to completion, not that a certain performance threshold was met.

Performance Test PR Builder

---

repose-aggregator/commons/commons-utilities/src/main/java/org/openrepose/commons/utils/http/ServiceClientResponse.java
repose-aggregator/commons/commons-utilities/src/test/groovy/org/openrepose/commons/utils/http/ServiceClientResponseTest.groovy
repose-aggregator/components/filters/saml-policy-translation-filter/src/main/scala/org/openrepose/filters/samlpolicy/SamlIdentityClient.scala
repose-aggregator/tests/functional-test-framework/src/main/groovy/org/openrepose/framework/test/mocks/MockIdentityV2Service.groovy
repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/attributemappingvalidation/AttributeMappingPolicyValidationFilterTest.groovy
repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlAttributeMappingTest.groovy
repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/samlpolicy/SamlFlow20Test.groovy

This was just to add/update missing tests around XML support now that it is becoming the more common format due to the ability to add comments.

REP-6818 Confirm XML SAML Support

---

repose-aggregator/core/repose-core/src/main/scala/org/openrepose/powerfilter/ReposeFilterChain.scala

This is variation of applying additional processing as pseudo-filters (i.e., intrafilter logging and metrics) that uses Scala functional capabilities.

REP-6038 Functional approach to filter chain processing

---

repose-aggregator/core/repose-core/src/main/scala/org/openrepose/powerfilter/ReposeRouter.scala

The primary purpose of this fix is to allow builds to complete and jobs to pass again.

Adding a router bean stub to satisfy the new servlet

---

repose-aggregator/core/repose-core-api/src/main/java/org/openrepose/core/systemmodel/config/Filter.java

Addressing some of my own comments on #1949 (and proving to myself that this works).

REP-6969 Cleaning up the Filter class

---

versions/8.9.1.0/release-notes.html

Fixing the release notes anchor

---

repose-aggregator/src/docs/asciidoc/index.adoc

I made some minor corrections. There are more opportunities, but I wanted to start with this.

Updates index.adoc

---

repose-aggregator/components/filters/herp-filter/src/main/scala/org/openrepose/filters/herp/HerpFilter.scala
repose-aggregator/components/filters/herp-filter/src/test/scala/org/openrepose/filters/herp/HerpFilterTest.scala
repose-aggregator/docs/src/asciibinder/welcome/release-notes.adoc
repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/herp/highly-efficient-record-processor.cfg.xml
repose-aggregator/tests/functional-tests/src/integrationTest/groovy/features/filters/herp/HerpSimpleTest.groovy

Down the rabbit hole! Based on: https://github.com/rackerlabs/repose/pull/2008

REP-7310 Fixing HERP Query Parameter Decoding

---

README.adoc
configuration/com.checkmarx.jenkins.CxScanBuilder.xml

This was a successful build after all of these changes:
https://jenkins-jenkins.devapps.rsi.rackspace.net/job/repose-checkmarx/444/

REP-7613 Updating Checkmarx Usage

---

repose-aggregator/docs/src/asciibinder/welcome/release-notes.adoc
repose-aggregator/docs/src/asciibinder/welcome/ver-9-upgrade-notes.adoc

Adding a note about the http.connection.max-status-line-garbage attribute removal

---

versions/9.0.0.0/welcome/release-notes.html
versions/9.0.0.0/welcome/ver-9-upgrade-notes.html

[GH Pages] Adding a note about the http.connection.max-status-line-garbage attribute removal
